-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301001&flag=1&year_id=1983&quarter_id=1","1983","韦发南","广西植物","中国楠属(Phoebe Nees)植物分类补志","7","10","1","本文为《中国植物志》楠属(Phoebe Nees)编著后对疑难标本的继续研究,现报导2个新种并归并1个种。文中所引标本,除Poilane 1285外,均存本所标本室。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","韦发南","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国楠属(Phoebe Nees)植物分类补志","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文为《中国植物志》楠属(Phoebe Nees)编著后对疑难标本的继续研究,现报导2个新种并归并1个种。文中所引标本,除Poilane 1285外,均存本所标本室。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301001&flag=1");
-- sleeping for 1.16 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301002&flag=1&year_id=1983&quarter_id=1","1983","卫兆芬","广西植物","中国无忧花属、仪花属和紫荆属资料","11","17","1","无忧花属 Saraca Linn. 1.云南无忧花(新拟) Saraca griffithiana Prain in Journ. Asiat. Soc. Bengal 66(2): 419.1887; G. F. P. Zuijderh. in Blumea 15: 417. 1967.","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","卫兆芬","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国无忧花属、仪花属和紫荆属资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","无忧花属 Saraca Linn. 1.云南无忧花(新拟) Saraca griffithiana Prain in Journ. Asiat. Soc. Bengal 66(2): 419.1887; G. F. P. Zuijderh. in Blumea 15: 417. 1967.","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301002&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1
REPLACE INTO publications(pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301003&flag=1&year_id=1983&quarter_id=1","甘长飞","广西植物","毛花猕猴桃一新变型","18","18","1","白色毛花猕猴桃 新变型 Actinidia eriantha Benth. form. alba C. F. Gan, f. nov. A typo receditfloribus albis. Zhejiang: Qingyuan-Xian, May 22, 1982, G. F. Gan 101 (Type, con-","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","甘长飞","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","毛花猕猴桃一新变型","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","白色毛花猕猴桃 新变型 Actinidia eriantha Benth. form. alba C. F. Gan, f. nov. A typo receditfloribus albis. Zhejiang: Qingyuan-Xian, May 22, 1982, G. F. Gan 101 (Type, con-","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301003&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301004&flag=1&year_id=1983&quarter_id=1","1983","高成芝 李光照","广西植物","广西虎耳草科新植物","19","23","1","1.兴安梅花草 别名:山梅花 新种 图1 Parnassia xinganensis C. Z Gao et G. Z. Li, sp. nov. Affinis Parnassiae reophilae Hance, a qua foliis ellipticis vel obovatoellipticis; petalis ellipticis, 9—10 mm longis, e basi in unguem abrupte contractis; staminodiis divergenter trilobis, lobo medio lobis lateralibus ang-","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","高成芝 李光照","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西虎耳草科新植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","1.兴安梅花草 别名:山梅花 新种 图1 Parnassia xinganensis C. Z Gao et G. Z. Li, sp. nov. Affinis Parnassiae reophilae Hance, a qua foliis ellipticis vel obovatoellipticis; petalis ellipticis, 9—10 mm longis, e basi in unguem abrupte contractis; staminodiis divergenter trilobis, lobo medio lobis lateralibus ang-","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301004&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301005&flag=1&year_id=1983&quarter_id=1","1983","林有润 黄奏球","广西植物","蕲州地区的蕲艾、青蒿、黄花蒿与茵陈的考订","25","31","1","蕲州是我国中药材主要产地之一,是湖北省蕲春县的一个集镇,,是我国中医药大师李时珍的家乡。该地区生长的菊科蒿属植物Artemisia Linn。颇多,其中入药的有十余种,并在李时珍《本草纲目》中曾有记载。这里仅对该地区常见入药的蕲艾、青蒿、黄花蒿与茵陈结合《本草纲目》记载的材料作初步的考订。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","林有润 黄奏球","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","蕲州地区的蕲艾、青蒿、黄花蒿与茵陈的考订","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","蕲州是我国中药材主要产地之一,是湖北省蕲春县的一个集镇,,是我国中医药大师李时珍的家乡。该地区生长的菊科蒿属植物Artemisia Linn。颇多,其中入药的有十余种,并在李时珍《本草纲目》中曾有记载。这里仅对该地区常见入药的蕲艾、青蒿、黄花蒿与茵陈结合《本草纲目》记载的材料作初步的考订。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301005&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301006&flag=1&year_id=1983&quarter_id=1","1983","苏宗明","广西植物","广西亚热带中山针阔混交林","33","42","1","广西亚热带地区没有很高大的山体,植被的垂直分布不出现亚高山常绿针叶林带,但在比较高大的山体,海拔1300米以上的地带,有中山针阔混交林的分布。这种类型有自己固有的群落学特点,在高级分类单位上应作为一种类型并在垂直带谱中给予应有的位置。广西中山针阔混交林有冷杉(Abies)混交林,铁杉(Tsuga)混交林、罗汉松(Podocarpus)混交林、银杉(cathaya)混交林四个群系组和七个群系。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","苏宗明","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西亚热带中山针阔混交林","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","广西亚热带地区没有很高大的山体,植被的垂直分布不出现亚高山常绿针叶林带,但在比较高大的山体,海拔1300米以上的地带,有中山针阔混交林的分布。这种类型有自己固有的群落学特点,在高级分类单位上应作为一种类型并在垂直带谱中给予应有的位置。广西中山针阔混交林有冷杉(Abies)混交林,铁杉(Tsuga)混交林、罗汉松(Podocarpus)混交林、银杉(cathaya)混交林四个群系组和七个群系。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301006&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301007&flag=1&year_id=1983&quarter_id=1","1983","朱亮锋 陆碧瑶 徐丹 罗友娇","广西植物","阳春砂仁叶油和广宁绿壳砂仁叶油化学成分的初步研究","43","47","1","本文报导应用气相色谱/质谱/计算机联用方法,分析了阳春砂仁叶油和广宁绿壳砂仁叶油的化学成分,分别鉴定出19和17个化学成分。两者相同的化学成分有:α-蒎烯、樟脑烯、β-蒎烯,γ-松油烯、3-已烯醇-[1]、异蒎樟脑酮、松油醇-[4)、α-松油醇以及对-α-聚伞花醇和麝香草酚等。这些化学成分占全油的70％以上。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","朱亮锋 陆碧瑶 徐丹 罗友娇","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","阳春砂仁叶油和广宁绿壳砂仁叶油化学成分的初步研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文报导应用气相色谱/质谱/计算机联用方法,分析了阳春砂仁叶油和广宁绿壳砂仁叶油的化学成分,分别鉴定出19和17个化学成分。两者相同的化学成分有:α-蒎烯、樟脑烯、β-蒎烯,γ-松油烯、3-已烯醇-[1]、异蒎樟脑酮、松油醇-[4)、α-松油醇以及对-α-聚伞花醇和麝香草酚等。这些化学成分占全油的70％以上。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301007&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301008&flag=1&year_id=1983&quarter_id=1","1983","朱亮锋 陆碧瑶 徐丹","广西植物","中国砂仁属植物精油化学成分的研究(一)——阳春砂仁和广宁绿壳砂仁","48","52","1","阳春砂仁为我国著名中药材,广宁绿壳砂仁亦可入药,功效与阳春砂仁相仿,单产比阳春砂仁高。我们应用色谱和色谱/质谱联用方法,分析了它们的种子精油化学成分,分别鉴定出23和25个化学成分。两者相同的成分有α-蒎烯,β-菰烯,樟脑,龙脑,乙酸龙脑酯等16个,其中主要化学成分如樟脑,香叶烯,柠檬烯,樟脑烯,乙酸龙脑酯,龙脑等含量一致","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","朱亮锋 陆碧瑶 徐丹","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国砂仁属植物精油化学成分的研究(一)——阳春砂仁和广宁绿壳砂仁","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","阳春砂仁为我国著名中药材,广宁绿壳砂仁亦可入药,功效与阳春砂仁相仿,单产比阳春砂仁高。我们应用色谱和色谱/质谱联用方法,分析了它们的种子精油化学成分,分别鉴定出23和25个化学成分。两者相同的成分有α-蒎烯,β-菰烯,樟脑,龙脑,乙酸龙脑酯等16个,其中主要化学成分如樟脑,香叶烯,柠檬烯,樟脑烯,乙酸龙脑酯,龙脑等含量一致","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301008&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1
REPLACE INTO publications(pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301009&flag=1&year_id=1983&quarter_id=1","黄正福 梁木源 黄陈光 李瑞高","广西植物","猕猴桃果实性状及营养成分的初步研究","53","56+66","1","猕猴桃为我国特产果品,果实芳香多汁,酸甜适口,风味佳美,营养价值高,可供鲜食和加工成罐头、果酱、果汁、果酒、果干、果脯、果晶等食品,深受世界各国的重视,成为一种新兴的栽培果树。 我国是猕猴桃的分布中心,资源丰富,种类繁多,据报导我国有猕猴桃92种(变种、变","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","黄正福 梁木源 黄陈光 李瑞高","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","猕猴桃果实性状及营养成分的初步研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","猕猴桃为我国特产果品,果实芳香多汁,酸甜适口,风味佳美,营养价值高,可供鲜食和加工成罐头、果酱、果汁、果酒、果干、果脯、果晶等食品,深受世界各国的重视,成为一种新兴的栽培果树。 我国是猕猴桃的分布中心,资源丰富,种类繁多,据报导我国有猕猴桃92种(变种、变","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301009&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301010&flag=1&year_id=1983&quarter_id=1","1983","谭文澄 戴策刚 李崇略 谢忠满","广西植物","生长素、细胞分裂素和三十烷醇对米兰空中压条生根的影响","57","65","1","采用滤纸法经对比试验及正交设计试验研究了混合生长素（萘乙酸和吲哚丁酸等量混合物）单用或与苄基腺嘌呤及三十烷醇相配合,对小叶米兰（Aglaia odorata Lour. var. microphyllina DC.,）空中压条生根的影响。发现三类生长物质适当配合或仅用混合生长素,都能大大改善米兰空中压条生根的质量,对加速繁殖有肯定作用。三因素最佳配合每枝压条的用量是:混合生长素3.0,苄基腺嘌呤0.075,三十烷醇10-4毫克。在生产上每枝压条单用混合生长素1.5—3.0毫克亦可获得增加生根数目与根总长度以及提早生根的效果。 讨论了生长物质作用的可能原因,滤纸法及正交设计用于农业生物学试验的优点。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","谭文澄 戴策刚 李崇略 谢忠满","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","生长素、细胞分裂素和三十烷醇对米兰空中压条生根的影响","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","采用滤纸法经对比试验及正交设计试验研究了混合生长素（萘乙酸和吲哚丁酸等量混合物）单用或与苄基腺嘌呤及三十烷醇相配合,对小叶米兰（Aglaia odorata Lour. var. microphyllina DC.,）空中压条生根的影响。发现三类生长物质适当配合或仅用混合生长素,都能大大改善米兰空中压条生根的质量,对加速繁殖有肯定作用。三因素最佳配合每枝压条的用量是:混合生长素3.0,苄基腺嘌呤0.075,三十烷醇10-4毫克。在生产上每枝压条单用混合生长素1.5—3.0毫克亦可获得增加生根数目与根总长度以及提早生根的效果。 讨论了生长物质作用的可能原因,滤纸法及正交设计用于农业生物学试验的优点。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301010&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198301011&flag=1&year_id=1983&quarter_id=1","1983","邓春匡","广西植物","广西硅藻羽纹纲——无壳缝目、短壳缝目、单壳缝目植物初报","67","76","1","广西硅藻羽纹纲的无壳缝目、单壳缝目和短壳缝目的种类及分布情况,过去虽然有许多藻类工作者作了大量工作,但至目前为止,还未见正式报导。现根据本人1978年参加中国孢子植物志《硅藻志》工作以来所采到的标本,选择了103号,进行酸处理及分类鉴定,初步鉴定属于羽纹纲无壳缝目的硅藻有8属11种20变种2变型、短壳缝目1属6种3变种、单壳缝","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","邓春匡","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西硅藻羽纹纲——无壳缝目、短壳缝目、单壳缝目植物初报","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","广西硅藻羽纹纲的无壳缝目、单壳缝目和短壳缝目的种类及分布情况,过去虽然有许多藻类工作者作了大量工作,但至目前为止,还未见正式报导。现根据本人1978年参加中国孢子植物志《硅藻志》工作以来所采到的标本,选择了103号,进行酸处理及分类鉴定,初步鉴定属于羽纹纲无壳缝目的硅藻有8属11种20变种2变型、短壳缝目1属6种3变种、单壳缝","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301011&flag=1");
-- sleeping for 1.62 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301012&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301013&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301014&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301015&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301016&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301017&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301018&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198301019&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302001&flag=1&year_id=1983&quarter_id=2","1983","黄淑美","广西植物","福建马兜铃属一新种","81","82","2","福建马兜铃 新种(图) 一条根、小号山东瓜、浦梨(福建宁德) Aristolochia fujianensis S. M. Hwang, sp. nov. Affinis A. contortae Bunge, sed tota planta praeter folium vetustumsupra glabrum pilosa, pilis albis vel brunneolis vestitis.","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","黄淑美","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","福建马兜铃属一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","福建马兜铃 新种(图) 一条根、小号山东瓜、浦梨(福建宁德) Aristolochia fujianensis S. M. Hwang, sp. nov. Affinis A. contortae Bunge, sed tota planta praeter folium vetustumsupra glabrum pilosa, pilis albis vel brunneolis vestitis.","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302001&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302002&flag=1&year_id=1983&quarter_id=2","1983","李光照","广西植物","广西苗儿山杜鹃属一新种","83","85","2","兴安马银花 新种(图) 小乔木,高7米,树皮灰色。小枝近于圆形,中等纤细,当年生小枝紫色或淡紫色,近于无毛,去年生小枝灰色。叶近于革质,长圆形或长圆状椭圆形,长6—9(-11厘米),宽2—3(-4.3厘米),顶端渐尖或罕为突然锐尖,基部近于圆形或钝形,边缘全缘,上面绿色,下面淡绿色,中肋在上面稍凹陷,在下面微凸起,侧脉和小脉通常不明显;叶柄长1—1.5厘米,有稀疏的短柔毛或近于无毛。花单生,花梗长1.5—2厘米,初被稀疏而具腺的刚毛,其后无毛;花萼裂片卵形,淡绿色,长8毫米,宽6毫米,具睫毛,无腺体;花冠紫色,具5裂片,裂片倒卵形,长2.5—8厘米,宽1.8-2厘米;雄蕊5枚,较花冠","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李光照","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西苗儿山杜鹃属一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","兴安马银花 新种(图) 小乔木,高7米,树皮灰色。小枝近于圆形,中等纤细,当年生小枝紫色或淡紫色,近于无毛,去年生小枝灰色。叶近于革质,长圆形或长圆状椭圆形,长6—9(-11厘米),宽2—3(-4.3厘米),顶端渐尖或罕为突然锐尖,基部近于圆形或钝形,边缘全缘,上面绿色,下面淡绿色,中肋在上面稍凹陷,在下面微凸起,侧脉和小脉通常不明显;叶柄长1—1.5厘米,有稀疏的短柔毛或近于无毛。花单生,花梗长1.5—2厘米,初被稀疏而具腺的刚毛,其后无毛;花萼裂片卵形,淡绿色,长8毫米,宽6毫米,具睫毛,无腺体;花冠紫色,具5裂片,裂片倒卵形,长2.5—8厘米,宽1.8-2厘米;雄蕊5枚,较花冠","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302002&flag=1");
-- sleeping for 1.61 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302003&flag=1&year_id=1983&quarter_id=2","1983","丘华兴 韩英兰","广西植物","新疆的沙戟属植物","87","89","2","沙戟属(Chrozophora)分布于旧大陆,生于较干燥环境或沙漠,分布中心在地中海区——南亚大陆。解放后,我国科技工作者,对新疆荒漠进行大量的植物学调查工作,在伊犁河谷和准噶尔盆地南缘的玛纳斯河流域,先后采集到本属的沙戟(C.sabulosa)标本。作者在编写《中国植物志》和参加伊犁河谷植被调查过程中,对沙戟属植物进行研究,并鉴定华南植物研究所标本室、新疆八一农学院林学系标本室和北京植物研究所标本室的标本。现报导如下。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","丘华兴 韩英兰","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","新疆的沙戟属植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","沙戟属(Chrozophora)分布于旧大陆,生于较干燥环境或沙漠,分布中心在地中海区——南亚大陆。解放后,我国科技工作者,对新疆荒漠进行大量的植物学调查工作,在伊犁河谷和准噶尔盆地南缘的玛纳斯河流域,先后采集到本属的沙戟(C.sabulosa)标本。作者在编写《中国植物志》和参加伊犁河谷植被调查过程中,对沙戟属植物进行研究,并鉴定华南植物研究所标本室、新疆八一农学院林学系标本室和北京植物研究所标本室的标本。现报导如下。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302003&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302004&flag=1&year_id=1983&quarter_id=2","1983","魏秉刚","广西植物","广西担子菌名录(二)","90","94","2","本文是广西担子菌名录(一)的续篇,记载了82种、2变种,分属2个亚纲,6个目,18个科,47个属。这批标本绝大部分是笔者1979年垒1982年2月期间在广西龙州,宁明两县的(山王丌)岗自然保护区和桂林市郊雁山地区及金秀县所采集的。其中为我国新记录的有一种,以“**”符号表示;为广西新记录的有29种,以“*”符号表示。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","魏秉刚","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西担子菌名录(二)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文是广西担子菌名录(一)的续篇,记载了82种、2变种,分属2个亚纲,6个目,18个科,47个属。这批标本绝大部分是笔者1979年垒1982年2月期间在广西龙州,宁明两县的(山王丌)岗自然保护区和桂林市郊雁山地区及金秀县所采集的。其中为我国新记录的有一种,以“**”符号表示;为广西新记录的有29种,以“*”符号表示。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302004&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302005&flag=1&year_id=1983&quarter_id=2","1983","林鹏 胡继添","广西植物","广西的红树林","95","102","2","本文主要讨论广西沿海的红树林的植物种类成分、外貌、适应形态学特点、群落类型和演替规律,以及生产管理问题。 该地区的红树植物种类计有8科、12属、12种,以红树科植物占优势。群落类型有:白骨壤群落、桐花树群落、秋茄-桐花树群落、红海榄群落、木榄群落、木榄-桐花树群落、桐花树-海漆稀树群落和红海榄+秋茄-桐花树群落等。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","林鹏 胡继添","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西的红树林","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文主要讨论广西沿海的红树林的植物种类成分、外貌、适应形态学特点、群落类型和演替规律,以及生产管理问题。 该地区的红树植物种类计有8科、12属、12种,以红树科植物占优势。群落类型有:白骨壤群落、桐花树群落、秋茄-桐花树群落、红海榄群落、木榄群落、木榄-桐花树群落、桐花树-海漆稀树群落和红海榄+秋茄-桐花树群落等。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302005&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302006&flag=1&year_id=1983&quarter_id=2","1983","李信贤 胡舜士","广西植物","从苗儿山木本植物区系的特点谈桂东北山地造林树种的选择","103","110","2","一个地区目前的植物区系是过去自然环境经过长期变化累积的产物。组成植物区系的种的生态生物学特性也是在长期历史条件下形成的。因此,在同一地区范围内,根据植物区系的特点来考虑造林树种的选择,引种或栽培本地区土生土长的野生经济植物,就容易取得成功,是一种既科学又经济实用的好办法。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李信贤 胡舜士","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","从苗儿山木本植物区系的特点谈桂东北山地造林树种的选择","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","一个地区目前的植物区系是过去自然环境经过长期变化累积的产物。组成植物区系的种的生态生物学特性也是在长期历史条件下形成的。因此,在同一地区范围内,根据植物区系的特点来考虑造林树种的选择,引种或栽培本地区土生土长的野生经济植物,就容易取得成功,是一种既科学又经济实用的好办法。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302006&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302007&flag=1&year_id=1983&quarter_id=2","1983","罗士扬 陈云英","广西植物","试论河池地区农业生态系统建设","111","116","2","本文通过收集农业生态系统的有关数据,以河池地区实况为例,叙述了保持生态平衡的意义,阐明了农业生态系统的现状,分析了影响农业生态系统的主要因素,提出了根据自然资源和社会资源,采取分区建设以达到建立一个合理的农业生态系统的战略性意见。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","罗士扬 陈云英","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","试论河池地区农业生态系统建设","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文通过收集农业生态系统的有关数据,以河池地区实况为例,叙述了保持生态平衡的意义,阐明了农业生态系统的现状,分析了影响农业生态系统的主要因素,提出了根据自然资源和社会资源,采取分区建设以达到建立一个合理的农业生态系统的战略性意见。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302007&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302008&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302008&flag=1&year_id=1983&quarter_id=2","1983","周良才","广西植物","罗汉果栽培枝术","117","120","2","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302008&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","周良才","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","罗汉果栽培枝术","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302008&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302009&flag=1&year_id=1983&quarter_id=2","1983","张碧玉","广西植物","罗汉果花粉生活力与其贮藏能力的研究","121","126","2","罗汉果系雌雄异株植物,栽培品种均需人工授粉才能结实。在实践中,由于花期不遇,给生产带来严重的影响。因而对罗汉果花粉生活力及贮藏能力的探索,使在人工授粉条件下,调节花粉的缺余,对提高结实力和增强杂交育种的效果都有重要意义。鉴于罗汉果花粉生活力及其贮藏能力的研究尚未见有报导,我们于1980——1982年进行了花粉生活力、花粉萌发动态及花粉贮藏试验,现将试验结果报告如下。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","张碧玉","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","罗汉果花粉生活力与其贮藏能力的研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","罗汉果系雌雄异株植物,栽培品种均需人工授粉才能结实。在实践中,由于花期不遇,给生产带来严重的影响。因而对罗汉果花粉生活力及贮藏能力的探索,使在人工授粉条件下,调节花粉的缺余,对提高结实力和增强杂交育种的效果都有重要意义。鉴于罗汉果花粉生活力及其贮藏能力的研究尚未见有报导,我们于1980——1982年进行了花粉生活力、花粉萌发动态及花粉贮藏试验,现将试验结果报告如下。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302009&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302010&flag=1&year_id=1983&quarter_id=2","1983","梁倩华 罗紫娟 吴佳德","广西植物","甘蔗组织培养育苗的培养基代用品试验","127","132","2","引言 几年来,我区甘蔗组织培养工作取得很大成绩。现在组织苗已大面积用于生产,加速了良种推广,因而受到群众的欢迎。然而,组织苗如按常规方法培养,所用的药品特别是琼脂,激素和蔗糖的价格比较高,为寻求成本低、效果好的代用品,特于1980年进行试验,本文报导这一试验的结果。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","梁倩华 罗紫娟 吴佳德","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","甘蔗组织培养育苗的培养基代用品试验","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","引言 几年来,我区甘蔗组织培养工作取得很大成绩。现在组织苗已大面积用于生产,加速了良种推广,因而受到群众的欢迎。然而,组织苗如按常规方法培养,所用的药品特别是琼脂,激素和蔗糖的价格比较高,为寻求成本低、效果好的代用品,特于1980年进行试验,本文报导这一试验的结果。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302010&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302011&flag=1&year_id=1983&quarter_id=2","1983","贺善英","广西植物","MH诱导黄皮形成小子果实的试验初报","133","136","2","黄皮又名黄枇Clausena lansium(Lour.)Skeels(C.wampi Blarico),芸香科黄皮属。两广,福建、台湾、四川、云南等省普遍栽培。果实富含维生素C,每100克果汁中含40.4—61.7毫克,还含有糖,有机酸和果胶。除鲜食外,可加工制成果冻、果酱、盐渍、糖渍、蜜饯、果干、清凉饮料,能助消化。此外,据古医书记载,能疏郁行气,止痛退热,治气胀腹痛等。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","贺善英","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","MH诱导黄皮形成小子果实的试验初报","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","黄皮又名黄枇Clausena lansium(Lour.)Skeels(C.wampi Blarico),芸香科黄皮属。两广,福建、台湾、四川、云南等省普遍栽培。果实富含维生素C,每100克果汁中含40.4—61.7毫克,还含有糖,有机酸和果胶。除鲜食外,可加工制成果冻、果酱、盐渍、糖渍、蜜饯、果干、清凉饮料,能助消化。此外,据古医书记载,能疏郁行气,止痛退热,治气胀腹痛等。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302011&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302012&flag=1&year_id=1983&quarter_id=2","1983","邓立杰","广西植物","几种氧化酶活性与植物对二氧化硫抗性的研究——植物本底及受污染后酶活性大小与抗性的关系","137","143","2","对27种不同抗性等级植物本底（未经污染处理的正常植物）多酚氧化酶、抗坏血酸氧化酶和过氧化物酶活性测定结果,植物本底多酚氧化酶活性与抗性有呈负相关的趋势,抗坏血酸氧化酶和过氧化物酶活性大小与抗性不具规律性。 对植物受不同浓度SO2污染后酶活性变化分析结果看出,蚬木（抗性植物）和汗斑草（敏感植物）在浓度达受阈前,多酚氧化酶、抗坏血酸氧化酶和过氧化物酶均有随浓度的升高而酶活性逐渐增大的趋势,仅是不同的酶其活性高峰在不同浓度梯度中出现迟早不同而己。在污染浓度达受伤阈后,随着浓度的继续增大,酶活性逐渐下降。而白蝉（抗性植物）和大猪屎青（敏感植物）有的酶具有规律性,有的酶不具有这种规律性。 用使可见伤害达50％的SO2污染汗斑草后4小时（一次污染）,过氧化物酶活性为0.34（未受污染的为12.69）,仅为未受污染的2.68％,降低了97.32％,但24小时后为7.68,为未受污染的60.52％,比受污染后4小时提高了57.84％,72小时后为8.52,为未受污染的67.13％,比受污染后4小时提高了65.45％。多酚氧化酶亦具有这种规律性。说明二氧化硫对这两种酶的抑制作用是可逆的。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","邓立杰","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","几种氧化酶活性与植物对二氧化硫抗性的研究——植物本底及受污染后酶活性大小与抗性的关系","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","对27种不同抗性等级植物本底（未经污染处理的正常植物）多酚氧化酶、抗坏血酸氧化酶和过氧化物酶活性测定结果,植物本底多酚氧化酶活性与抗性有呈负相关的趋势,抗坏血酸氧化酶和过氧化物酶活性大小与抗性不具规律性。 对植物受不同浓度SO2污染后酶活性变化分析结果看出,蚬木（抗性植物）和汗斑草（敏感植物）在浓度达受阈前,多酚氧化酶、抗坏血酸氧化酶和过氧化物酶均有随浓度的升高而酶活性逐渐增大的趋势,仅是不同的酶其活性高峰在不同浓度梯度中出现迟早不同而己。在污染浓度达受伤阈后,随着浓度的继续增大,酶活性逐渐下降。而白蝉（抗性植物）和大猪屎青（敏感植物）有的酶具有规律性,有的酶不具有这种规律性。 用使可见伤害达50％的SO2污染汗斑草后4小时（一次污染）,过氧化物酶活性为0.34（未受污染的为12.69）,仅为未受污染的2.68％,降低了97.32％,但24小时后为7.68,为未受污染的60.52％,比受污染后4小时提高了57.84％,72小时后为8.52,为未受污染的67.13％,比受污染后4小时提高了65.45％。多酚氧化酶亦具有这种规律性。说明二氧化硫对这两种酶的抑制作用是可逆的。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302012&flag=1");
-- sleeping for 1.48 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198302013&flag=1&year_id=1983&quarter_id=2","1983","王献溥","广西植物","从国家公园的意义和作用谈广西武鸣大明山保护区的经营管理问题","145","151","2","大家知道,国家公园是保护区的一种类型。建立国家公园的条件,不仅要求所在地的自然条件和生物特点是某一生物地理区域有代表性的地段,自然景观保护要较好,面积要较大,而且也要天然风景比较优美,交通比较方便,以便接纳广大群众参观游览,使人们在身临其境中受到自然界的薰陶,接受一次环境教育课,以培养人们了解自然、热爱自然,从而使保护自然和合理利用改造自然的伟大事业,有更广阔的群众基础。许多国家在发","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","王献溥","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","从国家公园的意义和作用谈广西武鸣大明山保护区的经营管理问题","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","大家知道,国家公园是保护区的一种类型。建立国家公园的条件,不仅要求所在地的自然条件和生物特点是某一生物地理区域有代表性的地段,自然景观保护要较好,面积要较大,而且也要天然风景比较优美,交通比较方便,以便接纳广大群众参观游览,使人们在身临其境中受到自然界的薰陶,接受一次环境教育课,以培养人们了解自然、热爱自然,从而使保护自然和合理利用改造自然的伟大事业,有更广阔的群众基础。许多国家在发","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302013&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302014&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302015&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302016&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302017&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302018&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198302019&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303001&flag=1&year_id=1983&quarter_id=3","1983","李秉滔","广西植物","广西大戟科新种和新分布","167","170","3","灌木,通常高3米,枝条细,粗3—5毫米,树皮近灰色,具细条纹,小枝具翅,无毛。叶薄纸质,椭圆形至卵状长圆形,无毛;中脉细,两面凸起,侧脉纤细,5—7对,两面稍凸起,未达叶缘而网结,叶柄长不及2毫米,无毛;托叶挟三角形,长3—4毫米,基部扩大,近耳形,顶端急尖。花腋生,单朵或稀2朵簇生,萼片和花盘互生,无花辦。雄花:花梗丝状,长3—3.5厘米,基部被微柔毛;萼片4枚,覆瓦状排列,披针形,长4.5毫米,","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李秉滔","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西大戟科新种和新分布","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","灌木,通常高3米,枝条细,粗3—5毫米,树皮近灰色,具细条纹,小枝具翅,无毛。叶薄纸质,椭圆形至卵状长圆形,无毛;中脉细,两面凸起,侧脉纤细,5—7对,两面稍凸起,未达叶缘而网结,叶柄长不及2毫米,无毛;托叶挟三角形,长3—4毫米,基部扩大,近耳形,顶端急尖。花腋生,单朵或稀2朵簇生,萼片和花盘互生,无花辦。雄花:花梗丝状,长3—3.5厘米,基部被微柔毛;萼片4枚,覆瓦状排列,披针形,长4.5毫米,","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303001&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303002&flag=1&year_id=1983&quarter_id=3","1983","张永田","广西植物","中国大戟科植物志资料(二)","171","176","3","与银叶巴豆的区别在于植物体上贴伏的鳞片边缘稍睫毛状,鳞片中间有刚毛状刺毛。 广西:张宗享、王善龄 4051(模式)。 越南:中越考察队1514。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","张永田","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国大戟科植物志资料(二)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","与银叶巴豆的区别在于植物体上贴伏的鳞片边缘稍睫毛状,鳞片中间有刚毛状刺毛。 广西:张宗享、王善龄 4051(模式)。 越南:中越考察队1514。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303002&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303003&flag=1&year_id=1983&quarter_id=3","1983","谭沛祥","广西植物","广西杜鹃花研究(二)","177","187","3","1.广西杜鹃 新种 图1 (映山红亚属,映山红组) 灌木,高2米;小枝纤细,被平贴铁锈色糙伏毛,后浙无毛。与紫花杜鹃 Rh.mar iae Hance有近缘,但叶薄革质,侧脉在背面部份隐晦,花冠无斑点,裂片长圆形,有凸尖,雄蕊常4枚,易于区别。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","谭沛祥","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西杜鹃花研究(二)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","1.广西杜鹃 新种 图1 (映山红亚属,映山红组) 灌木,高2米;小枝纤细,被平贴铁锈色糙伏毛,后浙无毛。与紫花杜鹃 Rh.mar iae Hance有近缘,但叶薄革质,侧脉在背面部份隐晦,花冠无斑点,裂片长圆形,有凸尖,雄蕊常4枚,易于区别。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303003&flag=1");
-- sleeping for 1.09 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303004&flag=1&year_id=1983&quarter_id=3","1983","方鼎 王育生","广西植物","广西铁木属一新种","189","191","3","乔木,高15—17米,胸径21—30厘米,树皮灰褐色,粗糙;老枝暗紫褐色,疏生不甚明显的褐色细小皮孔,变无毛,幼枝密被黄褐色长柔毛;芽椭圆形或狭卵形,长3—5毫米,芽鳞阔卵形,疏被短柔毛或无毛,边具缘毛。叶互生,卵形,稀狭卵形,长5—10.5厘米,宽2.5—5厘米,顶端渐尖,稀短浙尖,基部微心形,稍偏斜,上面疏生长柔毛或近无毛,背面灰绿色,密被短柔毛,中脉上面下凹,被开展的长柔毛,背面突起,基部密被其余疏被长柔毛,侧脉14—20对,脉间距离宽达6毫米,上面下凹,被短柔毛,背面突","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","方鼎 王育生","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西铁木属一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","乔木,高15—17米,胸径21—30厘米,树皮灰褐色,粗糙;老枝暗紫褐色,疏生不甚明显的褐色细小皮孔,变无毛,幼枝密被黄褐色长柔毛;芽椭圆形或狭卵形,长3—5毫米,芽鳞阔卵形,疏被短柔毛或无毛,边具缘毛。叶互生,卵形,稀狭卵形,长5—10.5厘米,宽2.5—5厘米,顶端渐尖,稀短浙尖,基部微心形,稍偏斜,上面疏生长柔毛或近无毛,背面灰绿色,密被短柔毛,中脉上面下凹,被开展的长柔毛,背面突起,基部密被其余疏被长柔毛,侧脉14—20对,脉间距离宽达6毫米,上面下凹,被短柔毛,背面突","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303004&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303005&flag=1&year_id=1983&quarter_id=3","1983","罗金裕","广西植物","广西黄色山茶花一新种","192","194","3","常绿灌木,高2—4米;树皮灰褐色,无毛。顶芽淡绿色,长圆锥状,长1.5—2.5厘米;芽鳞6—10枚,覆瓦状排列,密被银色短柔毛。叶革质,长椭圆形,长7.5—19厘米,宽3.5—6厘米,先端急尖,基部楔形或近圆形;边缘具细锯齿,齿端具黑褐色腺状尖头;两面无毛,上面深绿色,下面淡绿色,散生黑褐色小腺点;侧脉9—13对,干后在腹面下陷,在背面突起,中脉在腹面稍突起,在背面强明显突起,网脉在上面不明显下陷,在下面明显突起,叶柄长1—1.2厘米,腹部有沟槽,无毛,绿色。花单生于叶腋或顶生,直径1.5—4厘","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","罗金裕","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西黄色山茶花一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","常绿灌木,高2—4米;树皮灰褐色,无毛。顶芽淡绿色,长圆锥状,长1.5—2.5厘米;芽鳞6—10枚,覆瓦状排列,密被银色短柔毛。叶革质,长椭圆形,长7.5—19厘米,宽3.5—6厘米,先端急尖,基部楔形或近圆形;边缘具细锯齿,齿端具黑褐色腺状尖头;两面无毛,上面深绿色,下面淡绿色,散生黑褐色小腺点;侧脉9—13对,干后在腹面下陷,在背面突起,中脉在腹面稍突起,在背面强明显突起,网脉在上面不明显下陷,在下面明显突起,叶柄长1—1.2厘米,腹部有沟槽,无毛,绿色。花单生于叶腋或顶生,直径1.5—4厘","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303005&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303006&flag=1&year_id=1983&quarter_id=3","1983","方鼎","广西植物","水竹叶属一新种","195","196","3","多年生水生草本,高达30厘米,具须根;茎匍匐,多分枝,上升,节间1.5—7厘米,粗 1—3 毫米,具条棱,被一列多细胞短柔毛。叶鞘长 5—6 毫米,口部密被多细胞睫毛;叶全部茎生,无毛,心形,稀卵形,长 1—3 厘米,宽 0.8—2 厘米,顶端急尖或钝,基部通常浅心形,抱茎,稀圆形,边全缘,无柄。花通常2—4朵簇生于叶腋;苞片卵状矩圆形,长5—7毫米,宽3毫米,膜质;花梗挺直,长约1.4厘米,果时可达2厘米,被短柔毛,中部行有一关节;萼片绿色,卵形,无毛,长约4毫米,宽约2.5毫","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","方鼎","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","水竹叶属一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","多年生水生草本,高达30厘米,具须根;茎匍匐,多分枝,上升,节间1.5—7厘米,粗 1—3 毫米,具条棱,被一列多细胞短柔毛。叶鞘长 5—6 毫米,口部密被多细胞睫毛;叶全部茎生,无毛,心形,稀卵形,长 1—3 厘米,宽 0.8—2 厘米,顶端急尖或钝,基部通常浅心形,抱茎,稀圆形,边全缘,无柄。花通常2—4朵簇生于叶腋;苞片卵状矩圆形,长5—7毫米,宽3毫米,膜质;花梗挺直,长约1.4厘米,果时可达2厘米,被短柔毛,中部行有一关节;萼片绿色,卵形,无毛,长约4毫米,宽约2.5毫","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303006&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303007&flag=1&year_id=1983&quarter_id=3","1983","万煜","广西植物","广西大花藤属一新种","197","199","3","草质缠绕藤本,茎中空,有条纹,无毛,叶柄间具一列小腺体,脱落。叶对生,膜质,三角状卵形,宽卵形或近圆卵形,长9—15.5厘米,宽6—11.5厘米,顶端骤锐尖,基部耳形,两耳叉开或相接,边缘全缘,上面散生下面脉上疏生微毛,后变无毛,中脉和侧脉上面平坦下面稍凸起,侧脉每边6—7条,弧曲上升近叶缘网结;叶柄长3—8.5厘米,被与叶片相同的毛,顶端具丛生的小腺体。聚伞花序伞形状或不规则总状,生于叶柄间;花序梗长2—7.5(—10.5)厘米;花梗长2—3厘米,基部具苞片,苞片披针形,长2","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","万煜","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西大花藤属一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","草质缠绕藤本,茎中空,有条纹,无毛,叶柄间具一列小腺体,脱落。叶对生,膜质,三角状卵形,宽卵形或近圆卵形,长9—15.5厘米,宽6—11.5厘米,顶端骤锐尖,基部耳形,两耳叉开或相接,边缘全缘,上面散生下面脉上疏生微毛,后变无毛,中脉和侧脉上面平坦下面稍凸起,侧脉每边6—7条,弧曲上升近叶缘网结;叶柄长3—8.5厘米,被与叶片相同的毛,顶端具丛生的小腺体。聚伞花序伞形状或不规则总状,生于叶柄间;花序梗长2—7.5(—10.5)厘米;花梗长2—3厘米,基部具苞片,苞片披针形,长2","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303007&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303008&flag=1&year_id=1983&quarter_id=3","1983","梁健英","广西植物","广西石灰岩石山一种新的果树——冬杧果","200","202","3","冬杧果,新种 Mangifera hiemalis J. Y. Liang, sp. nov. (Anacardiaccae) 常绿乔木,高达25米,胸径达110厘米;树皮灰褐色,不规则纵裂。小枝粗壮,具条纹,无毛。叶近革质,长圆形或长圆状倒披针形,长10—30(50)厘米,宽 3—8(14)厘米,先端急尖,基部楔形,无毛,中脉两面凸起,侧脉每边18—22(26)条,斜升,两面凸起,小脉两面明显呈网状;叶柄长(1.5)3—8(14.5)厘米,基部彭大。圆锥花序顶生,长12—","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","梁健英","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西石灰岩石山一种新的果树——冬杧果","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","冬杧果,新种 Mangifera hiemalis J. Y. Liang, sp. nov. (Anacardiaccae) 常绿乔木,高达25米,胸径达110厘米;树皮灰褐色,不规则纵裂。小枝粗壮,具条纹,无毛。叶近革质,长圆形或长圆状倒披针形,长10—30(50)厘米,宽 3—8(14)厘米,先端急尖,基部楔形,无毛,中脉两面凸起,侧脉每边18—22(26)条,斜升,两面凸起,小脉两面明显呈网状;叶柄长(1.5)3—8(14.5)厘米,基部彭大。圆锥花序顶生,长12—","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303008&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303009&flag=1&year_id=1983&quarter_id=3","1983","钟业聪","广西植物","广西大瑶山自然保护区植物区系资料","203","204","3","灌本,高2—5米。树皮灰褐色至黄褐色;嫩枝被黄褐色茸毛,老时变无毛,芽体密被灰黄色至黄褐色绢毛。叶互生,革质,椭圆形或卵状椭圆形,长8—15厘米,宽3—6匣米,先端渐尖,基部阔楔形至圆形,表面深绿色,无毛,背面淡绿色,被灰黄色疏长毛,干后两面密布小瘤状突起物,中脉在表面下陷,侧脉5—7对,在表面平坦或下陷,叶缘具腺状细锯齿。花通常单生,顶生或腋生,开放时直径4.2—4.5厘米,花柄极短,长2—3毫米;苞片和萼片约9枚,薄革质,易压碎,在外方的半圆形,长4—5毫米,宽4—6毫米,在內","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","钟业聪","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西大瑶山自然保护区植物区系资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","灌本,高2—5米。树皮灰褐色至黄褐色;嫩枝被黄褐色茸毛,老时变无毛,芽体密被灰黄色至黄褐色绢毛。叶互生,革质,椭圆形或卵状椭圆形,长8—15厘米,宽3—6匣米,先端渐尖,基部阔楔形至圆形,表面深绿色,无毛,背面淡绿色,被灰黄色疏长毛,干后两面密布小瘤状突起物,中脉在表面下陷,侧脉5—7对,在表面平坦或下陷,叶缘具腺状细锯齿。花通常单生,顶生或腋生,开放时直径4.2—4.5厘米,花柄极短,长2—3毫米;苞片和萼片约9枚,薄革质,易压碎,在外方的半圆形,长4—5毫米,宽4—6毫米,在內","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303009&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303010&flag=1&year_id=1983&quarter_id=3","1983","薛兆文 王学文 高洁 郭新弧","广西植物","安徽省唇形科植物地理分布新记录","205","209","3","近年来我们从事于安徽唇形科植物的研究。通过广泛收集资料和标本的采集,在目前已鉴定的标本中,确认为安徽省地理分布新记录的有三个属(Schnabclia Hand. -Mazz., Bostrychanthera Benth., Kinostemon Kudo) 9个种(其中包括前三个属中的三个种)。将为研究安徽植物区系和资源植物提供点资料。现整理初报如下。文后附这些新记录的植物于安徽的分布图(图1)和部分种的照片(图2)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","薛兆文 王学文 高洁 郭新弧","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","安徽省唇形科植物地理分布新记录","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","近年来我们从事于安徽唇形科植物的研究。通过广泛收集资料和标本的采集,在目前已鉴定的标本中,确认为安徽省地理分布新记录的有三个属(Schnabclia Hand. -Mazz., Bostrychanthera Benth., Kinostemon Kudo) 9个种(其中包括前三个属中的三个种)。将为研究安徽植物区系和资源植物提供点资料。现整理初报如下。文后附这些新记录的植物于安徽的分布图(图1)和部分种的照片(图2)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303010&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303011&flag=1&year_id=1983&quarter_id=3","1983","吴泽民","广西植物","两种木本植物染色体数目的研究","211","214","3","我国是区系植物十分丰富的国家,有许多特有种及优良用材树种,但其中大多数缺少细胞学研究,近年来我国植物学界虽作了大量的植物染色体的研究工作,但对于木本双子叶植物的染色体数目报导仍然不多。 作者对我国特产的喜树(Camptotheca acuminata Decne. )及优良树种香椿 (Toona sinensis(A. Juss. )Roem. )作了染色体计数的研究。该两种植物以前均未见有染色体数目的报导。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","吴泽民","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","两种木本植物染色体数目的研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","我国是区系植物十分丰富的国家,有许多特有种及优良用材树种,但其中大多数缺少细胞学研究,近年来我国植物学界虽作了大量的植物染色体的研究工作,但对于木本双子叶植物的染色体数目报导仍然不多。 作者对我国特产的喜树(Camptotheca acuminata Decne. )及优良树种香椿 (Toona sinensis(A. Juss. )Roem. )作了染色体计数的研究。该两种植物以前均未见有染色体数目的报导。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303011&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1
REPLACE INTO publications(pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303012&flag=1&year_id=1983&quarter_id=3","何有乾","广西植物","灵香草的一种严重病害调查研究初报","215","218+210","3","灵香草的斑枯病俗称“点蜡烛”病,历来是灵香草的毁灭性病害。此病分布于广西金秀县各个灵香草产区;融水、龙胜等灵香草产地亦有此病发生。一般发病率60～70％,严重的往往达80％～90％,甚至失收。如1980年8月,金秀县外贸局为扶植生产队发展灵香草生产,无偿拨给金秀二队种苗300斤,分给社员种植。灵香草生长到高约23—27厘米时,全部病死腐烂。因此,要发展灵香草生产,必须有效地防治这种病害。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","何有乾","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","灵香草的一种严重病害调查研究初报","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","灵香草的斑枯病俗称“点蜡烛”病,历来是灵香草的毁灭性病害。此病分布于广西金秀县各个灵香草产区;融水、龙胜等灵香草产地亦有此病发生。一般发病率60～70％,严重的往往达80％～90％,甚至失收。如1980年8月,金秀县外贸局为扶植生产队发展灵香草生产,无偿拨给金秀二队种苗300斤,分给社员种植。灵香草生长到高约23—27厘米时,全部病死腐烂。因此,要发展灵香草生产,必须有效地防治这种病害。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303012&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303013&flag=1&year_id=1983&quarter_id=3","1983","黄演濂","广西植物","中华猕猴桃大果型优株79—2的初步选育","219","222","3","我园于1978—1981年对赣北地区(瑞昌、庐山、德安、武宁、修水、永修、湖口、都昌、星子等县),进行了为期4年的资源调查和单株选优工作。在优株78—1、78—2、79—1、79—2、80—1、81—5—1之中选出最优的一株79—2系中华猕猴桃软毛变种(Actinidia chinensis var. chinensis),于1980年3月18日进行嫁接,把优株上的芽体嫁接在本园栽培的一年生砧木上,观察其优良的经济性状是否能够保持。经过1980—1982年8年的培育、观察,初步证明79—2确是一个价值很高,值得推广的优良株系。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","黄演濂","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中华猕猴桃大果型优株79—2的初步选育","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","我园于1978—1981年对赣北地区(瑞昌、庐山、德安、武宁、修水、永修、湖口、都昌、星子等县),进行了为期4年的资源调查和单株选优工作。在优株78—1、78—2、79—1、79—2、80—1、81—5—1之中选出最优的一株79—2系中华猕猴桃软毛变种(Actinidia chinensis var. chinensis),于1980年3月18日进行嫁接,把优株上的芽体嫁接在本园栽培的一年生砧木上,观察其优良的经济性状是否能够保持。经过1980—1982年8年的培育、观察,初步证明79—2确是一个价值很高,值得推广的优良株系。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303013&flag=1");
-- sleeping for 1.02 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198303014&flag=1&year_id=1983&quarter_id=3","1983","","广西植物","从资源管理区的意义和作用谈广西贺县滑水冲保护区的经营管理问题","223","228","3","自然保护事业是随着工农业生产的发展和科学技术的突飞猛进,为了保证自然资源最大限度地持续供应和维持自然界的生态平衡,以适应人们生活不断提高的要求下发展起来的。它已经成为国家经济建设的一个组成部分,并不只是自然爱好者所关心的事情。建立自然保护区是发展自然保护事业的一个重要方面。由于不同地区的自然条件和经济特点以及人们经营的目的和要求不同,自然保护区的类型是各种各样的。当然,不管是什么类型的自然保护区,保护是最首要的任务。资源管理区的目的在于使某些资源能持续下去,例如水源、木","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","从资源管理区的意义和作用谈广西贺县滑水冲保护区的经营管理问题","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","自然保护事业是随着工农业生产的发展和科学技术的突飞猛进,为了保证自然资源最大限度地持续供应和维持自然界的生态平衡,以适应人们生活不断提高的要求下发展起来的。它已经成为国家经济建设的一个组成部分,并不只是自然爱好者所关心的事情。建立自然保护区是发展自然保护事业的一个重要方面。由于不同地区的自然条件和经济特点以及人们经营的目的和要求不同,自然保护区的类型是各种各样的。当然,不管是什么类型的自然保护区,保护是最首要的任务。资源管理区的目的在于使某些资源能持续下去,例如水源、木","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303014&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303015&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303016&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303017&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303018&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198303019&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304001&flag=1&year_id=1983&quarter_id=4","1983","王文采","广西植物","中国吊石苣苔属校订","249","284","4","英国学者D. Don于1822年根据Lysionotus serratus D. Don建立了吊石苣苔属Lysionotus D. Don。到了1883年,另一英国学者C. B. Clarke 在A. de Candolle主编的《Monographiae Phanerogamarum》中发表了苦苣苔亚科 Cyrtandroideae专著《Cyrtandreae(Gesneriacearum tribus)》,在此书中将Lysionotus D. Don属放在芒毛苣苔群 Trichosporeae 中,并列举了3个种(L. serrafus D. Don, L. Confertus Clarke, L. pauciflorus Maxim.)。从那时一直到现在,据《Index Kewensis》及有关","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","王文采","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国吊石苣苔属校订","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","英国学者D. Don于1822年根据Lysionotus serratus D. Don建立了吊石苣苔属Lysionotus D. Don。到了1883年,另一英国学者C. B. Clarke 在A. de Candolle主编的《Monographiae Phanerogamarum》中发表了苦苣苔亚科 Cyrtandroideae专著《Cyrtandreae(Gesneriacearum tribus)》,在此书中将Lysionotus D. Don属放在芒毛苣苔群 Trichosporeae 中,并列举了3个种(L. serrafus D. Don, L. Confertus Clarke, L. pauciflorus Maxim.)。从那时一直到现在,据《Index Kewensis》及有关","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304001&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304002&flag=1&year_id=1983&quarter_id=4","1983","李树刚","广西植物","中国柿科植物志资料","285","290","4","笔者在编写《中国植物志》柿科过程中,发现了一些未经描述的分类群,现发表如下: 梵净山柿 新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李树刚","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国柿科植物志资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","笔者在编写《中国植物志》柿科过程中,发现了一些未经描述的分类群,现发表如下: 梵净山柿 新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304002&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304003&flag=1&year_id=1983&quarter_id=4","1983","彭泽祥","广西植物","中国白花丹科植物志资料","291","292","4","本变型与原变型不同之处在于:新枝上长硬毛短小(长不超过1毫米);叶坚纸质,通常窄倒披针形至长圆状倒披针形,上面常沿侧脉或隆纹无或有稀少的钙粒;花药较大,长1.8—2毫米;蒴果较小,长约3毫米。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","彭泽祥","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国白花丹科植物志资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本变型与原变型不同之处在于:新枝上长硬毛短小(长不超过1毫米);叶坚纸质,通常窄倒披针形至长圆状倒披针形,上面常沿侧脉或隆纹无或有稀少的钙粒;花药较大,长1.8—2毫米;蒴果较小,长约3毫米。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304003&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304004&flag=1&year_id=1983&quarter_id=4","1983","彭泽祥","广西植物","白花丹科植物名称铨释","293","294","4","笔者在编写《中国植物志》白花丹科时Plumbaginaceae对白花丹科植物中名进行了考证,本文是对白花丹科植物中名的一些解释。 1.白花丹科Plumbaginaceae 白花丹科(种子植物名称》118.1953)一名是从本科模式属—白花丹属Plumbago L. 而得名。以前,此科曾用日本名,称为矶松科(《植物学大","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","彭泽祥","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","白花丹科植物名称铨释","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","笔者在编写《中国植物志》白花丹科时Plumbaginaceae对白花丹科植物中名进行了考证,本文是对白花丹科植物中名的一些解释。 1.白花丹科Plumbaginaceae 白花丹科(种子植物名称》118.1953)一名是从本科模式属—白花丹属Plumbago L. 而得名。以前,此科曾用日本名,称为矶松科(《植物学大","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304004&flag=1");
-- sleeping for 1.1 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304005&flag=1&year_id=1983&quarter_id=4","1983","张秀实","广西植物","中国桑科资料(一)","295","306","4","本种极似对叶榕 F.hispida Linn.f.,但叶背面密被开展棕色糙毛,榕果(?)宽25—30毫米,无毛,成熟黄色,干后具纵沟槽,口部苞片为明显莲座状,基生苞片不明显,总花梗长5—10毫米可以区别。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","张秀实","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国桑科资料(一)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本种极似对叶榕 F.hispida Linn.f.,但叶背面密被开展棕色糙毛,榕果(?)宽25—30毫米,无毛,成熟黄色,干后具纵沟槽,口部苞片为明显莲座状,基生苞片不明显,总花梗长5—10毫米可以区别。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304005&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304006&flag=1&year_id=1983&quarter_id=4","1983","莫新礼 韦发南","广西植物","广西大瑶山植物区系资料","307","311","4","蔓生或近直立草本;茎具棱,密生灰白色长硬毛。叶纸质,椭圆形或卵形,长5—9厘米,宽2.5—4厘米,先端钝,基部狭楔形,边缘有疏齿,两面被灰色长硬毛;叶柄长1—1.5厘米,被长硬毛。聚伞花序具4—5朵花,连总梗长约1.5—2.5厘米,总梗及花梗均被长硬毛;花梗长0.8—1.5厘米,花萼钟状,长5—6毫米,脉不明显,萼齿5,近等大,披针形,边缘被长硬毛;花冠白色,长约5厘米,无毛,近二唇形,上唇较短,长约3.5毫米,先端钝,下唇3裂,中裂片长圆形,长约7毫米,宽约4毫长,先端钝圆,雄蕊","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","莫新礼 韦发南","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西大瑶山植物区系资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","蔓生或近直立草本;茎具棱,密生灰白色长硬毛。叶纸质,椭圆形或卵形,长5—9厘米,宽2.5—4厘米,先端钝,基部狭楔形,边缘有疏齿,两面被灰色长硬毛;叶柄长1—1.5厘米,被长硬毛。聚伞花序具4—5朵花,连总梗长约1.5—2.5厘米,总梗及花梗均被长硬毛;花梗长0.8—1.5厘米,花萼钟状,长5—6毫米,脉不明显,萼齿5,近等大,披针形,边缘被长硬毛;花冠白色,长约5厘米,无毛,近二唇形,上唇较短,长约3.5毫米,先端钝,下唇3裂,中裂片长圆形,长约7毫米,宽约4毫长,先端钝圆,雄蕊","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304006&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1
REPLACE INTO publications(pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304007&flag=1&year_id=1983&quarter_id=4","庄璇","广西植物","中国山榄科植物志资料","312","312","4","滇铁榄,新组合 Sinosideroxylon yunnanense(C.Y.Wu)H. Chuang, comb. nov. Planchonellu yunnanensis C. Y. Wu, 云南热带亚热带植物区系研究报告1:26,p1。24,t,1.1965;云南植物志1:311,图版73,图3-5,1977。 A,Aubreville(1963)以种子形态特征为分属标准之一。本种浆果卵圆形,种子长圆状卵圆形,具圆形、近基生的疤痕,因此将本种归入铁榄属","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","庄璇","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国山榄科植物志资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","滇铁榄,新组合 Sinosideroxylon yunnanense(C.Y.Wu)H. Chuang, comb. nov. Planchonellu yunnanensis C. Y. Wu, 云南热带亚热带植物区系研究报告1:26,p1。24,t,1.1965;云南植物志1:311,图版73,图3-5,1977。 A,Aubreville(1963)以种子形态特征为分属标准之一。本种浆果卵圆形,种子长圆状卵圆形,具圆形、近基生的疤痕,因此将本种归入铁榄属","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304007&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304008&flag=1&year_id=1983&quarter_id=4","1983","高成芝","广西植物","广西鼠李科植物志资料","313","316","4","作者在编写广西植物志鼠李科的过程中,发现了如下新植物,现写成本文,予以报导。 1.南丹雀梅藤 新种 图1","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","高成芝","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西鼠李科植物志资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","作者在编写广西植物志鼠李科的过程中,发现了如下新植物,现写成本文,予以报导。 1.南丹雀梅藤 新种 图1","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304008&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304009&flag=1&year_id=1983&quarter_id=4","1983","刘寿养","广西植物","广西赤车属一新种","317","318","4","翅茎赤车 新种 Pellionia caulialata S. Y. Liu, sp. nov. (Urticaceae) 多年生草本。茎粗状,下部匍匐,高达120厘米,少分枝,绿色,无毛,老吋紫色,具6条纵行波曲状阔翅,翅紫色,宽3—5毫米。卟柄长2—12毫;叶片草质,斜倒卵形或斜椭圆形,长6—22厘米,宽3—9.5厘米,顶端长浙尖,基部狭侧楔形,宽侧阔楔形或近","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","刘寿养","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西赤车属一新种","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","翅茎赤车 新种 Pellionia caulialata S. Y. Liu, sp. nov. (Urticaceae) 多年生草本。茎粗状,下部匍匐,高达120厘米,少分枝,绿色,无毛,老吋紫色,具6条纵行波曲状阔翅,翅紫色,宽3—5毫米。卟柄长2—12毫;叶片草质,斜倒卵形或斜椭圆形,长6—22厘米,宽3—9.5厘米,顶端长浙尖,基部狭侧楔形,宽侧阔楔形或近","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304009&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304010&flag=1&year_id=1983&quarter_id=4","1983","广西紫胶科技协作组","广西植物","紫胶虫广西天然乡土寄主植物的选择利用","319","325","4","紫胶,是紫胶虫寄生在某些寄生植物上吸食树液后分泌出来的一种紫红色胶质物。因此,寄主植物是生产紫胶的物质基础。 国内紫胶主要靠云南省生产,远不能满足社会主义建设需要。为了扩大紫胶产区,五十年代末期,我区开始引进紫胶虫种源发展紫胶生产。云南原产地的牛肋巴(钝叶黄檀)、泡","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","广西紫胶科技协作组","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","紫胶虫广西天然乡土寄主植物的选择利用","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","紫胶,是紫胶虫寄生在某些寄生植物上吸食树液后分泌出来的一种紫红色胶质物。因此,寄主植物是生产紫胶的物质基础。 国内紫胶主要靠云南省生产,远不能满足社会主义建设需要。为了扩大紫胶产区,五十年代末期,我区开始引进紫胶虫种源发展紫胶生产。云南原产地的牛肋巴(钝叶黄檀)、泡","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304010&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1
REPLACE INTO publications(pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304011&flag=1&year_id=1983&quarter_id=4","程菊英 唐改福","广西植物","茴香菖蒲挥发油成分研究初报","326","326","4","茴香菖蒲文名香菖蒲(Acorus illicioides F, N. Wei et Y. K. Lee; sp。nov. ined)系天南星科菖蒲属植物。民间用它治风湿骨痛;无名肿毒;消炎止痛。其挥发油具有浓郁的茴香香味,民间常用全草作为调香剂,所以民间又称狗肉香。 茴香菖蒲挥发油为淡黄色油状物,鲜叶得率2—4％,干叶得率4—6％,根为0.6—","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","程菊英 唐改福","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","茴香菖蒲挥发油成分研究初报","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","茴香菖蒲文名香菖蒲(Acorus illicioides F, N. Wei et Y. K. Lee; sp。nov. ined)系天南星科菖蒲属植物。民间用它治风湿骨痛;无名肿毒;消炎止痛。其挥发油具有浓郁的茴香香味,民间常用全草作为调香剂,所以民间又称狗肉香。 茴香菖蒲挥发油为淡黄色油状物,鲜叶得率2—4％,干叶得率4—6％,根为0.6—","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304011&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304012&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304012&flag=1&year_id=1983&quarter_id=4","1983","","广西植物","广西植物 总目录 第3卷","327","330","4","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304012&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西植物 总目录 第3卷","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304012&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304013&flag=1
REPLACE INTO publications(pdf,year,authors,journal,title,spage,epage,issue,guid,issn) values("http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=198304013&flag=1&year_id=1983&quarter_id=4","1983","","广西植物","广西植物 1983年 第3卷 第1—4期 学名索引","331","348","4","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304013&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西植物 1983年 第3卷 第1—4期 学名索引","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304013&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304014&flag=1
-- sleeping for 1.68 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304015&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304016&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304017&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304018&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=198304019&flag=1
