-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2470&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2470&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="675";
-- 10.3969/j.issn.1005-3395.2010.06.014
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","卢博彬;黄穗生;傅嘉欣;张永福;赵海燕;潘丽佳;杨小娜;刘成明","10.3969/j.issn.1005-3395.2010.06.014");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","LU Bo-bin;HUANG Sui-sheng;FU Jia-xin;ZHANG Yong-fu;ZHAO Hai-yan;PAN Li-jia;YANG Xiao-na;LIU Cheng-ming","10.3969/j.issn.1005-3395.2010.06.014");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The germination and seedling of immature seeds and embryos after anthesis 82~87 d of longan (Dimocarpus longan Lour. ‘Shixia’) were studied. The results showed that the germination and seedling rates of immature embryos sowed directly in clean sand were better than those of in vitro cultured immature seeds. Furthermore, although the germination time of immature embryos stored at 4℃ for 24 hours was slightly delayed in sand, there was no obvious inhibition effect on their germination rate and seedling growth. These results indicated that sowing directly in clean sand was a good way for immature seed and/or embryo rescue in sexual hybridization breeding of longan. ","10.3969/j.issn.1005-3395.2010.06.014");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.014");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.014");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Studies on Seed Germination and Seedling of Immature Seeds and Embryos of Longan ‘Shixia’","10.3969/j.issn.1005-3395.2010.06.014");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","石硖龙眼未成熟种子种胚的萌发及成苗的研究","10.3969/j.issn.1005-3395.2010.06.014");
-- sleeping for 2.86 seconds
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2476&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2476&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="696";
-- 10.3969/j.issn.1005-3395.2010.06.018
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","CUI Guang-rong","10.3969/j.issn.1005-3395.2010.06.018");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The main research progresses on Phalaenopsis in vitro culture were reviewed, including explants selection, embryogenesis and protocorm-like body induction, medium, culture condition and method, and browning control, eg. Meanwhile, the bioreactor, genetic transformation, mutation breeding and other biotechnology were summarized. The flower stalk, tip of shoots and seeds from adult plants were common used as explants, and do the leaf, tip of shoots, root tips from tube plantlets. The main factors of explants browning were type of medium, pH, temperature and the physiological state. The researches about mutational breeding and genetic transformation in Phalaenopsis were still at preliminary stage.","10.3969/j.issn.1005-3395.2010.06.018");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.018");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.018");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Research Progress on Phalaenopsis in vitro Culture and Related Biotechnology","10.3969/j.issn.1005-3395.2010.06.018");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","蝴蝶兰离体培养及其相关生物技术研究进展","10.3969/j.issn.1005-3395.2010.06.018");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2510&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2510&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="655";
-- 10.3969/j.issn.1005-3395.2010.06.010
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","纪光欣;谭玲玲;初庆刚","10.3969/j.issn.1005-3395.2010.06.010");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","JI Guang-xin;TAN Ling-ling;CHU Qing-gang","10.3969/j.issn.1005-3395.2010.06.010");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The distribution and development of mucilage cells of Anredera cordifolia (Tenore) Steenis were studied by using paraffin sectioning. The results showed that mucilage cells generally exist in stem, leaf and leaf stalk of A. cordifolia. They scattered single in the pith and cortex of stem, and existed in both palisade tissue and spongy tissue of leaf, which spongy tissue had more mucilage cells than palisade tissue. There was a few mucilage cells in leaf stalk distributed in cortexes around of vascular bundles. The development of mucilage cells could be divided into 4 stages, such as initial cell stage, vacuolation stage, mature stage, and disintegration stage. The mucilage cell originated in the sixth leaf primordium, and the development of mucilage cells are not synchronized to that of stem and leaf.","10.3969/j.issn.1005-3395.2010.06.010");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.010");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.010");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Anatomical Studies on the Distribution and Development of Mucilage Cells in Anredera cordifolia","10.3969/j.issn.1005-3395.2010.06.010");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","落葵薯粘液细胞分布及发育的解剖学研究","10.3969/j.issn.1005-3395.2010.06.010");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2518&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2518&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="685";
-- 10.3969/j.issn.1005-3395.2010.06.016
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","董志渊;王馨;李林玉;杨斌;严世武;杨丽英;李绍平","10.3969/j.issn.1005-3395.2010.06.016");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","DONG Zhi-yuan;WANG Xing;LI Lin-yu;YANG Bin;YAN Shi-wu;YANG Li-yin;LI Shao-ping","10.3969/j.issn.1005-3395.2010.06.016");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The meiosis and male gametophyte development of Erigeron breviscapus were observed by using squash and transparent preparation technology, and the relationship between the development stage and the flower morphological characteristics was discussed. The results showed that cytokinesis of microspore mother cells in meiosis was simultaneous type, tetrad was tetrahedral, and mature pollen grain was 3-celled. The morphological characteristics of inflorescence and bud had relation to process of meiosis and male gamete development. The stages of meiosis and male gametophyte development could be distinguished according to the length of bud.","10.3969/j.issn.1005-3395.2010.06.016");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.016");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.016");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Meiosis, Male Gametophyte Development and Flower Morphology of Erigeron breviscapus","10.3969/j.issn.1005-3395.2010.06.016");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","短葶飞蓬减数分裂、雄配子体发育过程及其对应的花部形态特征","10.3969/j.issn.1005-3395.2010.06.016");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2527&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2527&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="689";
-- 10.3969/j.issn.1005-3395.2010.06.017
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","范伟;李文静;付桂;张治礼","10.3969/j.issn.1005-3395.2010.06.017");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","FAN Wei;Li-wenjing;FU Gui;Zhang-zhili","10.3969/j.issn.1005-3395.2010.06.017");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","Sesuvium portulacastrum (Aizoaceae) is a perennial, berbaceous facultative halophyte naturally growing in the tropical and subtropical coastal areas. The advances in mechanism research of Sesuvium portulacastrum under drought, high salinity and heavy metal stresses were reviewed. Meanwhile, its potential value and probably application were also discussed.","10.3969/j.issn.1005-3395.2010.06.017");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.017");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.017");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Sesuvium portulacastrum, A Promising Hhalophyte in Research and Application","10.3969/j.issn.1005-3395.2010.06.017");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","一种兼具研究与应用开发价值的盐生植物——海马齿","10.3969/j.issn.1005-3395.2010.06.017");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2532&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2532&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="633";
-- 10.3969/j.issn.1005-3395.2010.06.007
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","龚琴;周劲松;张永夏;梁冠欣;陈红锋;邢福武","10.3969/j.issn.1005-3395.2010.06.007");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","GONG Qin;ZHOU Jin-song;ZHANG Yong-xia;LIANG Guan-xin;CHEN Hong-feng;XING Fu-wu","10.3969/j.issn.1005-3395.2010.06.007");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The internal transcribed sequence of the nuclear ribosomal DNA (nrDNA-ITS) was chosen as the target sequence to resolve the phylogeny of the genus Viola in China. 66 sequences (39 of which were reported for the first time) of 55 ingroup taxa were collected, with Hybanthus concolor and Scyphellandra pierrei as outgroups. Molecular phylogenetic trees strongly supported the monophyly of Sect. Viola, Sect. Diffusae, Sect. Bilobatae and Sect. Vaginatae. The close sister relationship among Subgen. Melanium, Sect. Viola and Sect. Trigonocarpae was revealed, however, the clade of Sect. Trigonocarpae got low support. Subgen. Dischidium was confirmed to have a very close relationship with Subgen. Chamaemelanium by maximum parsimony tree, but the two Sections (Sect. Longicalcaratae and Sect. Brevicalcaratae) under Subgen. Dischidium  should be combined together. Phylogenetic trees also showed that Pinnatae should be treated as a subsection under Sect. Adnatae. Besides, the systematic status of V. lucens, V. magnifica, V. dissecta and V. yunnanensis were discussed combining molecular results with morphologic characters.","10.3969/j.issn.1005-3395.2010.06.007");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.007");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.007");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Molecular Systematics of Genus Viola L. in China","10.3969/j.issn.1005-3395.2010.06.007");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","国产堇菜属的分子系统学研究","10.3969/j.issn.1005-3395.2010.06.007");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2556&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2556&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="621";
-- 10.3969/j.issn.1005-3395.2010.06.005
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","游惠明;何东进;刘进山;蔡昌棠;何小娟;游巍斌;朱乃新;叶贤双;王磊","10.3969/j.issn.1005-3395.2010.06.005");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","YOU Hui-ming;HE Dong-jin;LIU Jin-shan;CAI Chang-tang;HE Xiao-juan;YOU Wei-bin;ZHU Nai-xin;YE Xian-shuang;WANG Lei","10.3969/j.issn.1005-3395.2010.06.005");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en"," The natural water moisture and effective water holding capacity of coarse woody debris (CWD) in three typical forest ecosystems in Tianbaoyan National Nature Reserve were studied. The results showed that the water holding capacity of CWD was lowest in the Crytomeria fortunei forest；the water holding capacity was in order as fallen tree＞snags＞stumps in Rhododendron simiarum forest, and snags＞fallen tree＞stumps in Tsuga longibracteata and Crytomeria fortunei forests. The effective water holding capacity of CWD increased with decay class of CWD increment，as well as the natural moisture content of CWD.","10.3969/j.issn.1005-3395.2010.06.005");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.005");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.005");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","The Water Holding Capacity of Coarse Woody Debris in Three Typical Forest Types in Tianbaoyan National Nature Reserve","10.3969/j.issn.1005-3395.2010.06.005");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","天宝岩3种典型森林类型CWD持水能力的比较","10.3969/j.issn.1005-3395.2010.06.005");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2562&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2562&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="599";
-- 10.3969/j.issn.1005-3395.2010.06.002
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","朱丽薇;赵平;蔡锡安;曾小平;邹绿柳;王权","10.3969/j.issn.1005-3395.2010.06.002");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","ZHU Li-wei;ZHAO Ping;CAI Xi-an;ZENG Xiao-ping;ZOU Lv-liu;WANG Quan","10.3969/j.issn.1005-3395.2010.06.002");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","In order to understand water use characteristics of Schima superba plantation and their relationships with environmental factors, Granier’s thermal dissipation probes were applied to measure sap flow density of 15 trees in a typical plantation stand, in which environmental factors including photosynthetically active radiation (PAR), air relative humidity, air temperature and soil moisture were recorded synchronously. Stand transpiration (Jd) and canopy stomatal conductance (gs) were then calculated based on sap flow density, sapwood area, environmental humidity and temperature from December 2007 (dry season) and September 2008 (wet season). The results showed that trees with larger sapwood areas had greater contribution of stand transpiration. Jd was found to be significantly different during wet and dry seasons, which had an average of 21.1 g H2O s-1 in September but only 7.03 g H2O s-1 in December, indicating a dramatic seasonal variation of it. In the meantime, Jd was found to be significantly correlated with environmental factors, in which PAR had the largest correlation coefficient and followed by vapor pressure deficit (VPD), air relative humidity and air temperature in sequence. On the other hand, the maximum gs were calculated to be 30.8 mmol m-2s-1 and 19.7 mmol m-2s-1 in September and December, respectively. It had positive linear relationship with PAR but negative one with VPD when PAR was larger than 1000 μmol m-2s-1 and VPD was over 2 kPa. However, gs did not present any statistically significant relation with soil moisture either in July or December, indicating that soil moisture was not the major environmental factor influencing stand transpiration of S. superba during our study periods.","10.3969/j.issn.1005-3395.2010.06.002");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.002");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.002");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Characteristics of Transpiration and Canopy Stomatal Conductance of Schima superba Plantation and Their Responses to Environmental Factors","10.3969/j.issn.1005-3395.2010.06.002");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","荷木人工林蒸腾与冠层气孔导度特征及对环境因子的响应","10.3969/j.issn.1005-3395.2010.06.002");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2565&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2565&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="627";
-- 10.3969/j.issn.1005-3395.2010.06.006
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","郑道君;李海文;云勇;张浪;张治礼","10.3969/j.issn.1005-3395.2010.06.006");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","ZHENG Dao-jun;LI Hai-wen;YUN Yong;ZHANG Lang;ZHANG Zhi-li","10.3969/j.issn.1005-3395.2010.06.006");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en"," The habitat and natural regeneration capacity of Dracaena cambodiana Pierre ex Gagnep in Hainan Island and the extent of human damage to its wild population were investigated and analyzed, and its endangered reasons were also discussed. The results showed that D.cambodiana was a typical rock-associated plant species and mainly distributed in the high-temperature and less-rainfall regions. D. cambodiana usually grew in the gap of steep and bare limestone or granite, or in sandy loam soil alongside the rock, and its associated species were often some small trees and shrubs. Due to the unrestricted exploitation of the wild plants and the destruction of its habitats, the wild resources of D. cambodiana have been very limited. In natural conditions, there were three ways for the regeneration of D. cambodiana, including the reproduction through seeds and the sprouts from roots and stumps. However, under the existing habitats, all of them were unable to effectively enlarge their wild population. It was concluded that the original habitat destruction and the unrestricted exploitation were the external factors for the endangerment of D. cambodiana, and the failure of seed germination or seedling growth under the poor habitats was the internal and major factor causing its endangerment, both of which made the species in an endangered status.","10.3969/j.issn.1005-3395.2010.06.006");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.006");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.006");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Investigation on the Habitat and Natural Regeneration Capacity of Dracaena cambodiana Population","10.3969/j.issn.1005-3395.2010.06.006");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","海南龙血树种群生境及自然更新能力调查","10.3969/j.issn.1005-3395.2010.06.006");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2567&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2567&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="670";
-- 10.3969/j.issn.1005-3395.2010.06.013
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李永平;朱海生;温庆放;花秀凤;林珲","10.3969/j.issn.1005-3395.2010.06.013");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","LI Yong-ping;ZHU Hai-sheng;WEN Qing-fang;HUA Xiu-feng;LIN Hui","10.3969/j.issn.1005-3395.2010.06.013");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","ζ-carotene Desatura (ZDS) is one of the rate-limiting enzymes in the carotenoids biosynthetic pathway. The ZDS gene named as FaZDS was cloned from strawberry (Fragaria ananassa Duchesne) fruit using RT-PCR and RACE techniques. The results showed that the length of FaZDS cDNA was 2148 bp with an open reading frame of 1710 bp, which encoded a polypeptide of 569 amino acids. Homology analysis showed that the deduced ZDS protein was highly homologous to those from other species. Phylogenetic analysis also indicated that ZDS in strawberry was close to apple. Prokaryotic expression showed that recombinant FaZDS had highly expression in E. coli BL21. The FaZDS could express in flower, fruit and leaf by semi-quantitative RT-PCR analysis, with the order as flower > red fruit > pink fruit > white fruit > green fruit > leaf.","10.3969/j.issn.1005-3395.2010.06.013");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.013");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.013");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Cloning and Characterization of ζ-carotene Desatura Gene in Fragaria ananassa Duchesne","10.3969/j.issn.1005-3395.2010.06.013");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","草莓ζ-胡萝卜素脱氢酶基因ZDS的克隆及特征分析","10.3969/j.issn.1005-3395.2010.06.013");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2570&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2570&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="607";
-- 10.3969/j.issn.1005-3395.2010.06.003
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","刘瑾;孙毓鑫;王法明;邹碧;李志安","10.3969/j.issn.1005-3395.2010.06.003");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","LIU Jin;SUN Yu-xin;WANG Fa-ming;ZOU Bi;LI Zhi-an","10.3969/j.issn.1005-3395.2010.06.003");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The carbon stock and total organic carbon (TOC) stability in soils of four typical plantations at 25-year-old in South China were investigated. The TOC content, labile carbon pool and soil microbial carbon in soil depth of 0~10 cm and 10~20 cm were determined. The results showed that soil TOC contents were in order as Acacia mangium > Acacia auriculaeformis > Pinus ellettii > Schima superba forest. Legume plantations (A. mangium and A. auriculaeformis) had markedly higher TOC content than non-legumes plantations (P. ellettii and S. superba). The TOC contents in two soil layers of A. mangium plantation were twice as high as those of S. superba plantation. S. superba plantation had the highest labile carbon pool (7.80 mg g-1) and the shortest turnover time (49 d). On the contrast, A. mangium plantation had the lowest labile carbon pool (2.14 mg g-1) and Clab/TOC (8.63%). A. mangium plantation had more stable TOC than other 3 plantations. The microbial carbon contents in surface soil layer (0~10 cm) were in order as A. mangium plantation>P. ellettii plantation>A. auriculaeformis plantation>S. superba plantation. It suggested more microbes favored transformation of litter into soil organic matter. At the subsoil layer (10~20 cm), soil microbial carbon in A. auriculaeformis plantation was significantly higher than those in others forest types, though it was very low in this layer. A. mangium plantation had the lowest microbial carbon content. It suggested that soil TOC accumulation in plantations was closely related to stability of organic matter and quantity of soil microbes.","10.3969/j.issn.1005-3395.2010.06.003");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.003");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.003");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Carbon Stock and TOC Stability in Soils of Four Typical Plantations in South China","10.3969/j.issn.1005-3395.2010.06.003");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","华南典型人工林土壤有机碳库及其稳定性特征研究","10.3969/j.issn.1005-3395.2010.06.003");
-- sleeping for 1.87 seconds
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2573&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2573&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="679";
-- 10.3969/j.issn.1005-3395.2010.06.015
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","许娜;储俊;夏海武;赵岩;钱立生","10.3969/j.issn.1005-3395.2010.06.015");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","XU Na;CHU Jun;XIA Hai-wu;ZHAO Yan;QIAN Li-sheng","10.3969/j.issn.1005-3395.2010.06.015");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The genetic transformation system of cucumber ‘New Jinchun 4’ mediated by Agrobacterium tumefaciens were studied. The cucumber leaves as explants were pre-cultured on MS + 1.0 mg L-1 6-BA + 0.15 mg L-1 IAA for 2 days. After infected by Agrobacterium (OD600=0.8, pH=5.7) for 8 min supplemented with 150 μmol/L acetosyringone (AS), the explants were co-cultured on MS + 1.0 mg L-1 6-BA + 0.15 mg L-1 IAA + 500 mg L-1 Carb + 40 mg L-1 Hyg for 2 days. The hpt gene were transformed successfully to regenerated plantlets by gus instantaneous expression and PCR test.","10.3969/j.issn.1005-3395.2010.06.015");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.015");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.015");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Establishment of Genetic Transformation System of Cucumber ‘New Jinchun 4’","10.3969/j.issn.1005-3395.2010.06.015");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","黄瓜‘新津春四号’遗传转化体系的建立","10.3969/j.issn.1005-3395.2010.06.015");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2576&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2576&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="593";
-- 10.3969/j.issn.1005-3395.2010.06.001
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","冯建孟;徐成东;董晓东","10.3969/j.issn.1005-3395.2010.06.001");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","FENG Jian-meng;XU Cheng-dong;DONG Xiao-dong","10.3969/j.issn.1005-3395.2010.06.001");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The spatial patterns and differentiation of species diversity of seed plants in Yunnan, China, were investigated based on distribution datasets of plant species at large scale, geographical information system and statistic methods. The results indicated that the discreteness of datasets of plant diversity and flora differentiation increased from families to genera and species. Compared with genera and species, the spatial variation and diversity centers of families were not obvious, which may be due to different historical periods in geology reflected by families, genera and species. The diversities of genera and species in southern Yunnan were richer than those of other areas except northwest Yunnan. The diversity centers of species were mainly observed in northwest Yunnnan, southern Yunnan, regions of Ailao Mountain, Wuliang Mountain, and Kunming region, which may be related to the geographical patterns of habitat heterogeneity and energy. Compared with families, the spatial variation of genera differentiation was more easily observed and showed similar patterns with species diversity, indicating significant correlation between plant diversity and flora differentiation. Compared with families, the centers of genera differentiation were obvious. On the whole, the spatial patterns of species diversity of seed plants and its differentiation were jointly shaped by habitat heterogeneity, energy and geological history.","10.3969/j.issn.1005-3395.2010.06.001");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.001");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.001");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","The Spatial Patterns of Species Diversity of Seed Plants and Its Differentiation in Yunnan, China","10.3969/j.issn.1005-3395.2010.06.001");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","云南地区种子植物多样性分布格局和多样性分化特点研究","10.3969/j.issn.1005-3395.2010.06.001");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2581&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2581&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="613";
-- 10.3969/j.issn.1005-3395.2010.06.004
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","刘艳;徐建民;钱国钦;吴炜;李宝富;吴世军;李宝琦","10.3969/j.issn.1005-3395.2010.06.004");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","LIU Yan;XU Jian-min;QIAN Guo-qin;WU Wei;LI Bao-fu;WU Shi-jun;LI Bao-qi","10.3969/j.issn.1005-3395.2010.06.004");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","The introduction experiments of 21 cold-tolerant species with 53 provenances of Eucalyptus at 5.5-year-old had been carried out, which survival and growth characteristics were studied. The results showed that there were significant differences among species and provenances in plant height, DBH and volume and survival. The tested species/provenances could be divided into five clusters by cluster analysis. The E. grandis, E. dunnii and E. benthamii, derived from Near Coffs Harbour NSW (20116) and NSW (20633 and 18788), respectively, had high volume growth at 5-year-old for 171.03 m3 hm-2, 158.61 m3 hm-2 and 110.962 m3 hm-2, respectively. The original altitude had little effect on growth and adaptability, whereas rainfall pattern was the key factor for introduction. The best species/provenances were introduced from 26&ordm;~30&ordm;S including southern Queensland, New South Wares and northern Victoria of Austria. E. dunnii, E. grandis, E. benthamii and E. saligna could tolerant the low temperature of -4℃～-4.5℃, so that they were suitable for introduction in mountane region of western Fujian.","10.3969/j.issn.1005-3395.2010.06.004");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.004");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.004");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Studies on Introduction of Cold-tolerant Tree Species /Provenances of Eucalyptus to Mountane Region in Western Fujian","10.3969/j.issn.1005-3395.2010.06.004");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","闽西山地耐寒桉属树种/种源引种试验研究","10.3969/j.issn.1005-3395.2010.06.004");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2583&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2583&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="665";
-- 10.3969/j.issn.1005-3395.2010.06.012
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","向闱;宁祖林;康明;黄宏文","10.3969/j.issn.1005-3395.2010.06.012");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","XIANG Wei;NING Zu-lin;KANG Ming;HUANG Hong-wen","10.3969/j.issn.1005-3395.2010.06.012");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","A total of 48501 expressed sequence tags (ESTs) of Castanea mollissima were obtained from database of Fagaceae Genomics, of which 8479 ESTs contain 12116 simple sequence repeats (SSRs) with motifs longer than 10 bp, with the frequency of SSRs up to 24.98%. Dinucleotide and trinucleotide repeats are the main EST-SSR types in Chinese chestnut, accounting for 38.05% and 42.20% of all EST-SSRs, respectively. The Chinese chestnut EST-SSR markers showed 100% transferability across the two endemic species to China, C. henryi and C. seguinii. There were 106, 108 and 101 polymorphic loci from 115 loci in C. mollissima, C. seguinii and C. henryi, respectively. While 260 out of the 575 alleles (45.22%) were shared among the three species, unique alleles in each species were also detected. These informative EST-SSR markers can be used in population genetic studies and comparative mapping of Chinese chestnuts.","10.3969/j.issn.1005-3395.2010.06.012");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.012");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.012");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Characteristic and Generality of EST-SSRs of Castanea mollissima","10.3969/j.issn.1005-3395.2010.06.012");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国板栗EST-SSR信息分析及其通用性","10.3969/j.issn.1005-3395.2010.06.012");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2588&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2588&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="650";
-- 10.3969/j.issn.1005-3395.2010.06.009
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李丽文;夏念和","10.3969/j.issn.1005-3395.2010.06.009");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","LI Li-wen;XIA Nian-he","10.3969/j.issn.1005-3395.2010.06.009");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","Pollinaria morphology of 17 species of Tylophora in China was observed under light microscope (LM). Four types of retinaculum (oblong, square, triangle and inverse triangle) and three types of pollinia (spheroidal, prolate and perprolate) were observed. The length of the caudicle, the shape and size of retinaculum and pollinia varied markedly. So these characters could be used to discriminate different species within Tylophora. Therefore, they were of significance in studying on classification of Tylophora.","10.3969/j.issn.1005-3395.2010.06.009");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.009");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.009");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Pollinaria Morphology of Tylophora (Asclepiadaceae)","10.3969/j.issn.1005-3395.2010.06.009");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","娃儿藤属（萝藦科）植物花粉器形态","10.3969/j.issn.1005-3395.2010.06.009");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2595&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2595&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="643";
-- 10.3969/j.issn.1005-3395.2010.06.008
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","杨永;张丽艳","10.3969/j.issn.1005-3395.2010.06.008");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","YANG Yong;ZHANG Li-yan","10.3969/j.issn.1005-3395.2010.06.008");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","Minor venation patterns of Syndiclis, Beilschmiedia, Potameia, Sinopora, and Endiandra were observed. The results showed that their venation patterns could be grouped into three types, the Type A with fine leaf reticulations bearing no free ending of veinlets, the Type B with fine leaf reticulations having free and simple ending of veinlets, and the Type C with coarse leaf reticulations possessing profusely branched ending of veinlets. Beilschmiedia was provided with the most diversified venation including all 3 types while other genera had only one of the 3 types each. Syndiclis, Sinopora, and the Chinese Endiandra shared the Type A venation pattern which was different from Potameia with the Type C venation pattern. ","10.3969/j.issn.1005-3395.2010.06.008");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.008");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.008");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Venation Pattern of Syndiclis Hook. f. and Its Related Genera","10.3969/j.issn.1005-3395.2010.06.008");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","油果樟属和近缘属的网脉结构式样","10.3969/j.issn.1005-3395.2010.06.008");
-- http://jtsb.scib.ac.cn/jtsb_en/ch/reader/view_abstract.aspx?flag=1&file_no=2617&journal_id=jtsb_cn
UPDATE publications SET pdf="http://jtsb.scib.ac.cn/jtsb_en/ch/reader/create_pdf.aspx?file_no=2617&flag=1&journal_id=jtsb_en&year_id=2010" WHERE issn="1005-3395" AND volume="18" AND spage="661";
-- 10.3969/j.issn.1005-3395.2010.06.011
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","武光南;夏念和;裴世山","10.3969/j.issn.1005-3395.2010.06.011");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","en","VU Quang Nam;XIA Nian-he;BUI The Doi","10.3969/j.issn.1005-3395.2010.06.011");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","en","Michelia mannii King (Magnoliaceae), a previously known species only in Bristish India, is newly recorded from Vietnam. It was found in primary limestone forest in Cuc Phuong National Park, Northern Vietnam and in Langbiang Plateau, Lam Dong Province, Southern Vietnam. The specimens of this species are being preserved in CHI, CPNP, IBSC, L, and VFU. ","10.3969/j.issn.1005-3395.2010.06.011");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","en","Journal of Tropical and Subtropical Botany","10.3969/j.issn.1005-3395.2010.06.011");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","热带亚热带植物学报","10.3969/j.issn.1005-3395.2010.06.011");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","Michelia mannii (Magnoliaceae)，A Newly Recorded Species from Vietnam","10.3969/j.issn.1005-3395.2010.06.011");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","越南木兰科植物新记录","10.3969/j.issn.1005-3395.2010.06.011");
