-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1000&flag=1&year_id=1986&quarter_id=z1","王文采","广西植物","中国苦苣苔科的研究(七)","1","15","z1","花萼钟状,5裂达基部;裂片条形。花冠白色或淡紫色(?);筒近筒形或漏斗状筒形;檐部二唇形,比简短,上唇正三角形或近半圆形,不分裂,下唇3浅裂。能育雄蕊2,位于下侧方,伸出;花丝着生于花冠简近中部或稍超过中部处,狭条形,直,有1脉;花药基着,宽卵形或长圆形,在腹面顶端连着或分离,药室平行,顶端不汇通。退化雄蕊或存在,3,位于上方,小,或不存在。花盘低杯状。雌蕊内藏;子房条形,2侧膜胎座不内伸,2裂,裂片极叉开,生有胚珠;花柱比子房短,柱头小,扁头状,与花柱等宽或比花柱稍","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","王文采","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国苦苣苔科的研究(七)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","花萼钟状,5裂达基部;裂片条形。花冠白色或淡紫色(?);筒近筒形或漏斗状筒形;檐部二唇形,比简短,上唇正三角形或近半圆形,不分裂,下唇3浅裂。能育雄蕊2,位于下侧方,伸出;花丝着生于花冠简近中部或稍超过中部处,狭条形,直,有1脉;花药基着,宽卵形或长圆形,在腹面顶端连着或分离,药室平行,顶端不汇通。退化雄蕊或存在,3,位于上方,小,或不存在。花盘低杯状。雌蕊内藏;子房条形,2侧膜胎座不内伸,2裂,裂片极叉开,生有胚珠;花柱比子房短,柱头小,扁头状,与花柱等宽或比花柱稍","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1000&flag=1");
-- sleeping for 1.63 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1001&flag=1&year_id=1986&quarter_id=z1","卫兆芬","广西植物","中国省藤属的研究","17","40","z1","省藤属是棕榈科中最大的一个属,约370种,主要分布于亚洲热带和亚热带地区,其中以马来西亚、印度尼西亚种类最多,印度、缅甸、越南、菲律宾等地和我国次之。此外,大洋洲北部海岸和非洲热带地区也有少数种类。 由于本属种类繁多,特征相差很大,加之植株高大且具利刺,对于标本采集十分不便,采得的标本又极不完整,所以给分类工作带来很大的困难。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","卫兆芬","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国省藤属的研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","省藤属是棕榈科中最大的一个属,约370种,主要分布于亚洲热带和亚热带地区,其中以马来西亚、印度尼西亚种类最多,印度、缅甸、越南、菲律宾等地和我国次之。此外,大洋洲北部海岸和非洲热带地区也有少数种类。 由于本属种类繁多,特征相差很大,加之植株高大且具利刺,对于标本采集十分不便,采得的标本又极不完整,所以给分类工作带来很大的困难。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1001&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1002&flag=1&year_id=1986&quarter_id=z1","丘华兴","广西植物","中国桑寄生科植物资料(二)","41","48","z1","我国桑寄生科(狭义的)共有8属,约49种、7变种。现续报道大苞鞘花属Elytranthe Blume 1个新记录种,离瓣寄生属Helixanthera Lour.产于云南1个新记录种及其描述和西藏2个种,桑寄生属Loranthus Jacq.2个种,梨果寄生属Scurrula Linn.3个种和钝果寄生属Taxillus Van Tiegh.4个种的分布区和标本引证,以及一些种类的寄生,异名和错误文献等。 桑寄生科植物对木本经济植物具有危害性,作者在云南、广西和广东野外工作时,注意到在局部地区,“桑寄生类”对栽培的油茶林、普洱茶林、石梓林、云南油杉林、栎林,柿树及风景区的庭园树的危害情况,已成为主要的植物病害。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","丘华兴","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国桑寄生科植物资料(二)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","我国桑寄生科(狭义的)共有8属,约49种、7变种。现续报道大苞鞘花属Elytranthe Blume 1个新记录种,离瓣寄生属Helixanthera Lour.产于云南1个新记录种及其描述和西藏2个种,桑寄生属Loranthus Jacq.2个种,梨果寄生属Scurrula Linn.3个种和钝果寄生属Taxillus Van Tiegh.4个种的分布区和标本引证,以及一些种类的寄生,异名和错误文献等。 桑寄生科植物对木本经济植物具有危害性,作者在云南、广西和广东野外工作时,注意到在局部地区,“桑寄生类”对栽培的油茶林、普洱茶林、石梓林、云南油杉林、栎林,柿树及风景区的庭园树的危害情况,已成为主要的植物病害。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1002&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1003&flag=1&year_id=1986&quarter_id=z1","罗献瑞 赵素云","广西植物","中国防巳科资料","49","61","z1","本文报道有关中国防巳科植物研究的一些资料,涉及青牛胆属(Tinospora)、细圆藤属(Pericampylus)和轮环藤属(Cyclea)三个属。考虑到青牛胆属和轮环藤属植物有较大的药用价值,而《中国植物志》防巳科的出版又尚需时日,故将这两属的分种检索表一并收入本文,供鉴定标本时参考。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","罗献瑞 赵素云","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国防巳科资料","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文报道有关中国防巳科植物研究的一些资料,涉及青牛胆属(Tinospora)、细圆藤属(Pericampylus)和轮环藤属(Cyclea)三个属。考虑到青牛胆属和轮环藤属植物有较大的药用价值,而《中国植物志》防巳科的出版又尚需时日,故将这两属的分种检索表一并收入本文,供鉴定标本时参考。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1003&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1004&flag=1&year_id=1986&quarter_id=z1","莫新礼 钟业聪","广西植物","广西金花茶新植物(二)","62","62","z1","作者原先对该植物的分类研究结果已确认为一新种,但经《植物分类学报》送有关专家审查后,降为金花茶Camellia chrysantha (Hu) Tuyuma的变种发表。及后,有的学者又把它视为与原变种无异而予以归并。作者曾一再对该植物作了较多的观察,对比研究,觉得其主要特征与金花茶的差异是相当明显的,不但花小,果小,而且花瓣开放时近平展,萼片及花瓣内面均被柔毛,边缘具流苏状小缘毛,这些特征是比较稳定的,而在金花茶是不存在的。同时其染色体组型亦有差异,因此,作者认为把它视为金花茶的一个变种也不适当,把它与金花茶视为一物更不客观,以提升为种较适宜。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","莫新礼 钟业聪","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西金花茶新植物(二)","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","作者原先对该植物的分类研究结果已确认为一新种,但经《植物分类学报》送有关专家审查后,降为金花茶Camellia chrysantha (Hu) Tuyuma的变种发表。及后,有的学者又把它视为与原变种无异而予以归并。作者曾一再对该植物作了较多的观察,对比研究,觉得其主要特征与金花茶的差异是相当明显的,不但花小,果小,而且花瓣开放时近平展,萼片及花瓣内面均被柔毛,边缘具流苏状小缘毛,这些特征是比较稳定的,而在金花茶是不存在的。同时其染色体组型亦有差异,因此,作者认为把它视为金花茶的一个变种也不适当,把它与金花茶视为一物更不客观,以提升为种较适宜。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1004&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1005&flag=1&year_id=1986&quarter_id=z1","吴兆洪","广西植物","秦仁昌分类系统(蕨类植物门)的历史渊源","63","78","z1","蕨类植物由于它在植物系统发育史上的重要地位,几百年来都受到植物学家们的注意。经过蕨类学家们几百年的探索,创见迭出,现在已发展成为植物学中一门独立的分支学科——蕨类植物学。对蕨类植物进行科学的研究可追溯到十六世纪。在十六世纪以前,植物分类学是按照用途(特别是药用)而分门别类的,过去蕨类植物的记载只是零散地见于一些有","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","吴兆洪","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","秦仁昌分类系统(蕨类植物门)的历史渊源","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","蕨类植物由于它在植物系统发育史上的重要地位,几百年来都受到植物学家们的注意。经过蕨类学家们几百年的探索,创见迭出,现在已发展成为植物学中一门独立的分支学科——蕨类植物学。对蕨类植物进行科学的研究可追溯到十六世纪。在十六世纪以前,植物分类学是按照用途(特别是药用)而分门别类的,过去蕨类植物的记载只是零散地见于一些有","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1005&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1006&flag=1&year_id=1986&quarter_id=z1","王献溥 李信贤","广西植物","广西兴安苗儿山保护区的植被","79","91","z1","苗儿山是南岭山地越城岭的主峰,广西第一高峰,海拔2141.5米。整个林区面积约80万亩,划为自然保护区约25万亩,境内森林茂密,生物资源丰富。有关苗儿山保护区的基本特点、经营管理方向等,我们已有专文论述,这里不再重复。本文着重对植被的主要类型及其分布情况作概括的论述,供有关方面参考。 虽然,苗儿山保护区范围主要由花岗岩和砂页岩发育的黄棕壤、黄壤和红壤所构成,都属酸性土壤,但山地海拔高程相差达1900米,加以人为生产活动的方式和强度不同的影响,所以,植被的类型是多种多样的。现分述如下:","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","王献溥 李信贤","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","广西兴安苗儿山保护区的植被","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","苗儿山是南岭山地越城岭的主峰,广西第一高峰,海拔2141.5米。整个林区面积约80万亩,划为自然保护区约25万亩,境内森林茂密,生物资源丰富。有关苗儿山保护区的基本特点、经营管理方向等,我们已有专文论述,这里不再重复。本文着重对植被的主要类型及其分布情况作概括的论述,供有关方面参考。 虽然,苗儿山保护区范围主要由花岗岩和砂页岩发育的黄棕壤、黄壤和红壤所构成,都属酸性土壤,但山地海拔高程相差达1900米,加以人为生产活动的方式和强度不同的影响,所以,植被的类型是多种多样的。现分述如下:","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1006&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1007&flag=1&year_id=1986&quarter_id=z1","陈守良 金岳杏 吴竹君","广西植物","从叶片表皮细胞结构讨论尾稃草属与臂形草属的分合问题","93","94+153","z1","尾稃草属Urochloa Beauv.与臂形草属Brachiaria Griseb.的外部形态很相似,中外禾本科分类学者对这两属分合问题存在不同看法。为此取该两属的国产11种,67份材料作叶片表皮细胞结构的观察研究,共拍摄显微照片22张。 制片方法:参见南京中山植物园研究论文集,1980年版。 两属11种叶片表皮的微形态特征的共性是硅细胞为哑铃形、节结形或十字形,气孔辅卫细胞为圆屋顶形,显示本两属应隶属于黍亚科Panicoideae,黍族Paniceae,雀稗亚族Paspalinae之下。但其脉间细胞结构可分析归纳如下:","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","陈守良 金岳杏 吴竹君","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","从叶片表皮细胞结构讨论尾稃草属与臂形草属的分合问题","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","尾稃草属Urochloa Beauv.与臂形草属Brachiaria Griseb.的外部形态很相似,中外禾本科分类学者对这两属分合问题存在不同看法。为此取该两属的国产11种,67份材料作叶片表皮细胞结构的观察研究,共拍摄显微照片22张。 制片方法:参见南京中山植物园研究论文集,1980年版。 两属11种叶片表皮的微形态特征的共性是硅细胞为哑铃形、节结形或十字形,气孔辅卫细胞为圆屋顶形,显示本两属应隶属于黍亚科Panicoideae,黍族Paniceae,雀稗亚族Paspalinae之下。但其脉间细胞结构可分析归纳如下:","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1007&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1008&flag=1&year_id=1986&quarter_id=z1","徐炳声 刘琰 陈铁山","广西植物","假百合核型的研究","95","98","z1","假百合,Notholirion bulbiliferum (Lingelsh.) Stearn [N.hyacinthinum (Wils.) Stapf]是百合科假百合属,Notholirion Wall.ex Boiss.的多年生草本植物,产于我国陕西、甘肃、四川、西藏和云南等省区;尼泊尔、锡金、不丹和印度也有分布。假百合陕西民间叫“太白米”,是一种药用植物。 假百合属共4种,做过染色体计数者3种。本文首次报道了假百合的染色体数目,并做了核型分析,旨在与百合属Lilium L.的核型作一比较,为探讨这两属间的亲缘关系提供必要的细胞学资料。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","徐炳声 刘琰 陈铁山","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","假百合核型的研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","假百合,Notholirion bulbiliferum (Lingelsh.) Stearn [N.hyacinthinum (Wils.) Stapf]是百合科假百合属,Notholirion Wall.ex Boiss.的多年生草本植物,产于我国陕西、甘肃、四川、西藏和云南等省区;尼泊尔、锡金、不丹和印度也有分布。假百合陕西民间叫“太白米”,是一种药用植物。 假百合属共4种,做过染色体计数者3种。本文首次报道了假百合的染色体数目,并做了核型分析,旨在与百合属Lilium L.的核型作一比较,为探讨这两属间的亲缘关系提供必要的细胞学资料。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1008&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1009&flag=1&year_id=1986&quarter_id=z1","李林初","广西植物","一些国产植物的染色体观察","99","105+157","z1","作者观察了我国13科19属22种植物的染色体,本文首次报道了5种植物的染色体核型(图1)。2n或n数为第一次记录。其中多种在国内尚未进行过研究(表1)。3种染色体数目为首次报告,2种植物的凭证标本及凭证玻片均藏复旦大学生物系植物标本室。 材料和方法 材料来源和实验用材见表1。截取1厘米左右长根尖,经0.002M 8-羟基喹啉在室温下预处理8—4小时,用卡诺氏液(3∶1的95％乙醇—冰醋酸)固定2—24小时。用1N盐酸60℃","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","李林初","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","一些国产植物的染色体观察","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","作者观察了我国13科19属22种植物的染色体,本文首次报道了5种植物的染色体核型(图1)。2n或n数为第一次记录。其中多种在国内尚未进行过研究(表1)。3种染色体数目为首次报告,2种植物的凭证标本及凭证玻片均藏复旦大学生物系植物标本室。 材料和方法 材料来源和实验用材见表1。截取1厘米左右长根尖,经0.002M 8-羟基喹啉在室温下预处理8—4小时,用卡诺氏液(3∶1的95％乙醇—冰醋酸)固定2—24小时。用1N盐酸60℃","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1009&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1010&flag=1&year_id=1986&quarter_id=z1","黄少甫 赵治芬 庄瑞林 徐炳声 周启仁 邱金兴","广西植物","多齿红山茶核型的分析","107","110","z1","多齿红山茶(Camellia polyodondta How ex Hu)又名宛田红花油茶,属于山茶属(Camellia L.)红山茶组(Sect.Camellia),特产我国广西,花瓣红色有条纹呈鳞片状和色斑,具较高的观赏价值,种子油可食用。本文继1981年对多齿红山茶的染色体数目报道后,对其核型做了分析。并在此基础上,对比了红山茶组的浙江红山茶(C.chekiangoleosa Hu),南山茶(C.semiserrata Chi)和白花南山茶(C.semiserrata var.albiflora Hu ex Huang)的核型,初步对这些","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","黄少甫 赵治芬 庄瑞林 徐炳声 周启仁 邱金兴","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","多齿红山茶核型的分析","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","多齿红山茶(Camellia polyodondta How ex Hu)又名宛田红花油茶,属于山茶属(Camellia L.)红山茶组(Sect.Camellia),特产我国广西,花瓣红色有条纹呈鳞片状和色斑,具较高的观赏价值,种子油可食用。本文继1981年对多齿红山茶的染色体数目报道后,对其核型做了分析。并在此基础上,对比了红山茶组的浙江红山茶(C.chekiangoleosa Hu),南山茶(C.semiserrata Chi)和白花南山茶(C.semiserrata var.albiflora Hu ex Huang)的核型,初步对这些","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1010&flag=1");
-- sleeping for 2.98 seconds
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1011&flag=1&year_id=1986&quarter_id=z1","卢天玲 廖汉刃","广西植物","宛田红花油茶的染色体核型研究","111","115","z1","在张宏达先生的山茶属分类系统中,宛田红花油茶是山茶属(Camellia Linn),红山茶组(Sect.Camellia)。该组是国外进行染色体研究最多的一个组,但进行核型分析的不多,国内在这方面有过研究,但宛田红花油茶的核型分析未见报道。 材料与方法 制片用的宛田红花油茶种子是广西壮族自治区林科所提供,采于该所物种园内。1984年11月采种沙藏,12月初转入25℃恒温箱中恒温培养,待幼根长至1—8厘米时取样。 截取根尖浸入饱和的对二氯苯溶液,在10℃恒温条件下,预处理10—13小时,然后转入","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","卢天玲 廖汉刃","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","宛田红花油茶的染色体核型研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","在张宏达先生的山茶属分类系统中,宛田红花油茶是山茶属(Camellia Linn),红山茶组(Sect.Camellia)。该组是国外进行染色体研究最多的一个组,但进行核型分析的不多,国内在这方面有过研究,但宛田红花油茶的核型分析未见报道。 材料与方法 制片用的宛田红花油茶种子是广西壮族自治区林科所提供,采于该所物种园内。1984年11月采种沙藏,12月初转入25℃恒温箱中恒温培养,待幼根长至1—8厘米时取样。 截取根尖浸入饱和的对二氯苯溶液,在10℃恒温条件下,预处理10—13小时,然后转入","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1011&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1012&flag=1&year_id=1986&quarter_id=z1","邹琦丽","广西植物","光叶红豆和花榈木核型比较","117","119","z1","作者已报道过花榈木(Ormosia henryi Prain)的核型,近来又进行了光叶红豆(Ormosia glaberrima Wu)的核型分析,现对这两种红豆的核型进行比较。 材料和方法 光叶红豆种子采自广西植物研究所标本园,凭证标本存广西植物研究所 种子经砂培萌发后取根尖,按常规法压片,铁矶——苏木精染色,叔丁醇退片,冷杉胶封片。选取染色体分散好的片进行核型分析。 结果与讨论 计数结果表明,光叶红豆的染色体数目为2n=16,和花榈木的染色体数目相同,与属的","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","邹琦丽","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","光叶红豆和花榈木核型比较","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","作者已报道过花榈木(Ormosia henryi Prain)的核型,近来又进行了光叶红豆(Ormosia glaberrima Wu)的核型分析,现对这两种红豆的核型进行比较。 材料和方法 光叶红豆种子采自广西植物研究所标本园,凭证标本存广西植物研究所 种子经砂培萌发后取根尖,按常规法压片,铁矶——苏木精染色,叔丁醇退片,冷杉胶封片。选取染色体分散好的片进行核型分析。 结果与讨论 计数结果表明,光叶红豆的染色体数目为2n=16,和花榈木的染色体数目相同,与属的","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1012&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1013&flag=1&year_id=1986&quarter_id=z1","成桂仁 金静兰 文永新 陈桂初","广西植物","灵香草化学成分的初步研究","121","129","z1","利用不同溶剂提取,柱层析分离,并通过色谱/质谱/计算机联用仪分析和检索,从灵香草中鉴定出100个已知化学成分。此外,还鉴定出蔗糖、β—谷甾醇、棕榈酸。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","成桂仁 金静兰 文永新 陈桂初","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","灵香草化学成分的初步研究","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","利用不同溶剂提取,柱层析分离,并通过色谱/质谱/计算机联用仪分析和检索,从灵香草中鉴定出100个已知化学成分。此外,还鉴定出蔗糖、β—谷甾醇、棕榈酸。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1013&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1014&flag=1&year_id=1986&quarter_id=z1","陆碧瑶 朱亮锋 吴德邻","广西植物","中国豆蔻属植物种子精油的主要化学成分及其与果实外部形态的相关性","131","139","z1","本文报道中国产14种豆蔻属Amomum植物种子的精油化学成分并探讨其主要成分与果实外部形态之相关性。按其精油所含的主要化学成分及其含量,初步可划分为三个类型:一类以阳春砂仁为代表,主含乙酸龙脑酯和樟脑;一类以草果,白豆蔻为代表,主含1,8-桉叶油素,除药用外亦可作调料;第三类如九翅砂仁,长果砂仁等主含其它成分,均未正式入药。本文可供寻找新的砂仁药源作参考。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","陆碧瑶 朱亮锋 吴德邻","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","中国豆蔻属植物种子精油的主要化学成分及其与果实外部形态的相关性","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","本文报道中国产14种豆蔻属Amomum植物种子的精油化学成分并探讨其主要成分与果实外部形态之相关性。按其精油所含的主要化学成分及其含量,初步可划分为三个类型:一类以阳春砂仁为代表,主含乙酸龙脑酯和樟脑;一类以草果,白豆蔻为代表,主含1,8-桉叶油素,除药用外亦可作调料;第三类如九翅砂仁,长果砂仁等主含其它成分,均未正式入药。本文可供寻找新的砂仁药源作参考。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1014&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1015&flag=1&year_id=1986&quarter_id=z1","王献溥","广西植物","关于受威胁的保护区及其解除对策","141","145","z1","在世界范围内,工业化和城市化的进程异常迅速,这当然是经济发展的标志,但是,能否也注意到自然资源的合理利用和保护以及保持生态环境不遭受破坏呢?这是人们所普遍关心的事。如果持肯定态度的话,那么,自然保护区的建设就是一项非常重要的任务了。所谓自然保护区就是要在世界不同的生物地理省范围内,都应划出一定的区域,尽量保持其自然状态的完整性或让其自然面貌得到应有的恢复,不再遭受各种人为活动的干扰,以便为人类经济和文化生活不同的需要服务。近年来,虽然保护区的建设在日新月异地发展,但是,还有许多地方由于认识上或实际上的困难等原因的影响,对建立自然保护区的重要性,","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","王献溥","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","关于受威胁的保护区及其解除对策","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","在世界范围内,工业化和城市化的进程异常迅速,这当然是经济发展的标志,但是,能否也注意到自然资源的合理利用和保护以及保持生态环境不遭受破坏呢?这是人们所普遍关心的事。如果持肯定态度的话,那么,自然保护区的建设就是一项非常重要的任务了。所谓自然保护区就是要在世界不同的生物地理省范围内,都应划出一定的区域,尽量保持其自然状态的完整性或让其自然面貌得到应有的恢复,不再遭受各种人为活动的干扰,以便为人类经济和文化生活不同的需要服务。近年来,虽然保护区的建设在日新月异地发展,但是,还有许多地方由于认识上或实际上的困难等原因的影响,对建立自然保护区的重要性,","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1015&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1016&flag=1&year_id=1986&quarter_id=z1","王献溥","广西植物","关于“濒危野生动植物国际贸易公约”简介","147","150","z1","最近,不少开发公司拟开展野生动植物国际贸易,这就必需了解和熟悉“濒危野生动植物国际贸易公约”的规定,办理必要的手续。为此,把这个公约略作介绍,以供有关方面参考。 一、“公约”产生的背景和经过 “濒危野生动植物贸易公约”(以下简称公约,英文缩写CITES,这几个字母的艺术写法似一头大象)是1972年联合国在瑞典首都斯德哥尔摩召开的人类环境会议上,鉴于国际野生动植物的贸易年产值已高达10亿美元,说明许多地方野生动植物已被过度开发利用,如不注意控制,就会引起许多动植物濒临灭绝的危险。为了控制贸易的规模,避免过分的利用,以保护野生动植物的生存,从而提供永续的利用,会议通过了一项提案:建议在各国政","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","王献溥","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","关于“濒危野生动植物国际贸易公约”简介","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","最近,不少开发公司拟开展野生动植物国际贸易,这就必需了解和熟悉“濒危野生动植物国际贸易公约”的规定,办理必要的手续。为此,把这个公约略作介绍,以供有关方面参考。 一、“公约”产生的背景和经过 “濒危野生动植物贸易公约”(以下简称公约,英文缩写CITES,这几个字母的艺术写法似一头大象)是1972年联合国在瑞典首都斯德哥尔摩召开的人类环境会议上,鉴于国际野生动植物的贸易年产值已高达10亿美元,说明许多地方野生动植物已被过度开发利用,如不注意控制,就会引起许多动植物濒临灭绝的危险。为了控制贸易的规模,避免过分的利用,以保护野生动植物的生存,从而提供永续的利用,会议通过了一项提案:建议在各国政","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1016&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1
REPLACE INTO publications(url,pdf,authors,journal,title,spage,epage,issue,abstract,guid,issn) values("http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1","http://www.guihaia-journal.com/ch/reader/create_pdf.aspx?file_no=1986Z1017&flag=1&year_id=1986&quarter_id=z1","","广西植物","“802”广增素在柑桔上应用的初步效果","151","151","z1","“802”广增素是广西植物研究所研制成功的一种新型植物生长调节剂。 为了进一步证实“802”广增素对柑桔的增产作用,我们于1985年春开始用广西植物研究所与桂林市临桂综合化工厂试产的“802”广增素在早熟温州蜜柑幼龄结果树上进行试验。所用浓度分别为50ppm、100ppm和150ppm,同时设一空白对照,喷以清水;各个处理和对照均重复3次,试验树的条件相对一致;分别在温州蜜柑的谢花期、幼果期、生理落果期和果实膨大期进行全树喷洒。采果时按正规实验方法进行取样、计量、分析和统计。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1","1000-3142");
REPLACE INTO multilingual(`key`,language,value,guid) values("authors","zh","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","en","","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("journal","zh","广西植物","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("title","zh","“802”广增素在柑桔上应用的初步效果","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1");
REPLACE INTO multilingual(`key`,language,value,guid) values("abstract","zh","“802”广增素是广西植物研究所研制成功的一种新型植物生长调节剂。 为了进一步证实“802”广增素对柑桔的增产作用,我们于1985年春开始用广西植物研究所与桂林市临桂综合化工厂试产的“802”广增素在早熟温州蜜柑幼龄结果树上进行试验。所用浓度分别为50ppm、100ppm和150ppm,同时设一空白对照,喷以清水;各个处理和对照均重复3次,试验树的条件相对一致;分别在温州蜜柑的谢花期、幼果期、生理落果期和果实膨大期进行全树喷洒。采果时按正规实验方法进行取样、计量、分析和统计。","http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1017&flag=1");
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1018&flag=1
-- http://www.guihaia-journal.com/ch/reader/view_abstract.aspx?file_no=1986Z1019&flag=1
